// Aftershock 2026 — festival definition.
//
// Pure data: no schedule is built here. buildFestival() in shared/festival.js
// turns this into placed blocks, lanes and grid bounds.
//
// GENERATED by scripts/gen-greencopper-festival.py — regenerate rather than
// hand-patching, or the next refresh will clobber the edit.
//
// Source: the festival's own Greencopper app data. The schedule page carries
// no times, only an app download link, but the JSON backing that app is
// served publicly:
//   https://goeventweb-static.greencopper.com/<project-hash>/<project-tag>/data/eng/shows.json
// with <project-hash> and <project-tag> read off the <goevent-web> element on
// the schedule page. These are therefore the festival's own published times,
// not a transcription.
//
// The sparse-looking grid is real: this is a Danny Wimmer rotating-stage
// festival, so despite the stage count only two or three acts play at once,
// sets are short (mostly 30-50 min) and there are genuine gaps. Press
// coverage that lists each set as running until the next one starts is
// chaining start times, and disagrees with the app for that reason.
//
// Format per set: [stageId, 'HH:MM start', 'HH:MM end', 'Artist']
//
// "The Point Stage pres. by Coors Light" is shortened to "The Point Stage"
// for display; the sponsor tag is noise in a grid column header.
//
// All times are PT (24h). Nothing crosses midnight (latest end 23:00).

const slug = 'aftershock-2026';

const stages = [
  { id: 'aftershock', name: 'Aftershock Stage', short: 'AFTR', color: '--brick-clay' },
  { id: 'shockwave',  name: 'Shockwave Stage', short: 'SHOCK', color: '--sunset-coral' },
  { id: 'point',      name: 'The Point Stage', short: 'POINT', color: '--dusk-purple' },
  { id: 'faultline',  name: 'Faultline Stage', short: 'FAULT', color: '--ocean-deep' },
  { id: 'epicenter',  name: 'Epicenter', short: 'EPI', color: '--jungle-green' },
];

const days = [
  { id: 'thu', name: 'Thursday', date: 'Oct 1' },
  { id: 'fri', name: 'Friday', date: 'Oct 2' },
  { id: 'sat', name: 'Saturday', date: 'Oct 3' },
  { id: 'sun', name: 'Sunday', date: 'Oct 4' },
];

// Each set: [stageId, start, end, artist]
const sets = {
  thu: [
    // ── Aftershock Stage ────────────────────────────────────────
    ['aftershock', '11:55', '12:20', 'Free Throw'],
    ['aftershock', '12:50', '13:20', 'Lit'],
    ['aftershock', '14:00', '14:30', 'We The Kings'],
    ['aftershock', '15:15', '15:50', 'Mayday Parade'],
    ['aftershock', '16:40', '17:25', 'Hot Mulligan'],
    ['aftershock', '18:20', '19:15', 'Sublime'],
    ['aftershock', '20:25', '21:55', 'My Chemical Romance'],

    // ── Shockwave Stage ─────────────────────────────────────────
    ['shockwave', '11:30', '11:55', 'LEAP'],
    ['shockwave', '12:20', '12:50', 'L.S. Dunes'],
    ['shockwave', '13:25', '13:55', 'Hawthorne Heights'],
    ['shockwave', '14:35', '15:10', 'The Starting Line'],
    ['shockwave', '15:55', '16:35', 'New Found Glory'],
    ['shockwave', '17:30', '18:15', 'The Used'],
    ['shockwave', '19:20', '20:20', 'The Offspring'],

    // ── The Point Stage pres. by Coors Light ────────────────────
    ['point', '12:05', '12:35', 'The Violent Hour'],
    ['point', '13:05', '13:40', 'Red'],
    ['point', '14:10', '14:45', 'Finger Eleven'],
    ['point', '15:15', '15:55', 'Apocalyptica'],
    ['point', '16:25', '17:10', 'Theory of a Deadman'],
    ['point', '17:40', '18:25', 'Nothing More'],
    ['point', '19:35', '20:25', 'The Pretty Reckless'],

    // ── Faultline Stage ─────────────────────────────────────────
    ['faultline', '11:35', '12:05', 'Primer 55'],
    ['faultline', '12:35', '13:05', 'Brujeria'],
    ['faultline', '13:40', '14:10', 'Ünloco'],
    ['faultline', '14:45', '15:15', 'Ill Niño'],
    ['faultline', '15:55', '16:25', 'The Union Underground'],
    ['faultline', '17:10', '17:55', 'Coal Chamber'],
    ['faultline', '18:45', '19:35', 'Sevendust'],
    ['faultline', '20:20', '21:15', 'Killswitch Engage'],

    // ── Epicenter ───────────────────────────────────────────────
    ['epicenter', '12:50', '13:20', 'Wind Walkers'],
    ['epicenter', '14:00', '14:30', 'The Word Alive'],
    ['epicenter', '15:15', '15:50', 'Caskets'],
    ['epicenter', '16:40', '17:20', 'Holding Absence'],
    ['epicenter', '18:20', '19:05', 'From Ashes To New'],
    ['epicenter', '21:10', '21:55', 'Starset'],
  ],

  fri: [
    // ── Aftershock Stage ────────────────────────────────────────
    ['aftershock', '11:30', '11:55', 'Silly Goose'],
    ['aftershock', '12:20', '12:50', 'Drowning Pool'],
    ['aftershock', '13:20', '14:00', 'P.O.D.'],
    ['aftershock', '14:45', '15:25', 'Insane Clown Posse'],
    ['aftershock', '16:15', '17:00', 'Cypress Hill'],
    ['aftershock', '17:55', '18:40', 'Public Enemy'],
    ['aftershock', '19:35', '20:35', 'Wu-Tang Clan'],
    ['aftershock', '21:45', '23:00', 'Limp Bizkit'],

    // ── Shockwave Stage ─────────────────────────────────────────
    ['shockwave', '11:55', '12:20', 'Haarper'],
    ['shockwave', '12:50', '13:15', 'HAYWIRE'],
    ['shockwave', '14:05', '14:40', 'DRAIN'],
    ['shockwave', '15:30', '16:10', 'Kublai Khan TX'],
    ['shockwave', '17:05', '17:50', 'Three 6 Mafia'],
    ['shockwave', '18:45', '19:30', 'Slaughter to Prevail'],
    ['shockwave', '20:40', '21:40', '$UICIDEBOY$'],

    // ── The Point Stage pres. by Coors Light ────────────────────
    ['point', '12:45', '13:15', 'Eyes Set To Kill'],
    ['point', '13:45', '14:15', 'Alesana'],
    ['point', '14:45', '15:20', 'Finch'],
    ['point', '15:50', '16:30', 'Atreyu'],
    ['point', '17:00', '17:40', 'Senses Fail'],
    ['point', '18:10', '18:50', 'Alexisonfire'],
    ['point', '19:20', '20:10', 'Underoath'],
    ['point', '20:50', '21:45', 'Coheed and Cambria'],

    // ── Faultline Stage ─────────────────────────────────────────
    ['faultline', '12:20', '12:45', 'Traverse The Abyss'],
    ['faultline', '13:15', '13:45', 'vianova'],
    ['faultline', '14:15', '14:45', 'Psychostick'],
    ['faultline', '15:20', '15:55', 'Nekrogoblikon'],
    ['faultline', '16:30', '17:05', 'Blue Medusa'],
    ['faultline', '17:35', '18:20', 'Cradle of Filth'],
    ['faultline', '20:00', '20:50', 'Chad Gray: Voice of Mudvayne & HELLYEAH'],
    ['faultline', '21:45', '22:45', 'Dethklok'],

    // ── Epicenter ───────────────────────────────────────────────
    ['epicenter', '12:20', '12:50', 'Rivers of Nihil'],
    ['epicenter', '13:20', '14:00', 'PeelingFlesh'],
    ['epicenter', '14:45', '15:25', 'Bodysnatcher'],
    ['epicenter', '16:15', '17:00', 'Spite'],
    ['epicenter', '17:55', '18:40', 'The Black Dahlia Murder'],
    ['epicenter', '19:40', '20:30', 'Paleface Swiss'],
  ],

  sat: [
    // ── Aftershock Stage ────────────────────────────────────────
    ['aftershock', '11:30', '12:00', 'Fear, And Loathing in Las Vegas'],
    ['aftershock', '12:30', '13:00', 'ivri'],
    ['aftershock', '13:30', '14:05', 'Blessthefall'],
    ['aftershock', '14:45', '15:20', 'Set It Off'],
    ['aftershock', '16:05', '16:45', 'Chiodos'],
    ['aftershock', '17:35', '18:20', 'Sleeping with Sirens'],
    ['aftershock', '19:20', '20:10', 'BABYMETAL'],
    ['aftershock', '21:25', '22:55', 'Pierce The Veil'],

    // ── Shockwave Stage ─────────────────────────────────────────
    ['shockwave', '12:00', '12:30', 'Austin Carlile: The Original Voice of Of Mice & Men'],
    ['shockwave', '13:00', '13:30', 'Escape The Fate'],
    ['shockwave', '14:05', '14:40', 'The Devil Wears Prada'],
    ['shockwave', '15:25', '16:00', 'The Wonder Years'],
    ['shockwave', '16:50', '17:30', 'Wage War'],
    ['shockwave', '18:25', '19:15', 'The Story So Far'],
    ['shockwave', '20:15', '21:20', 'A Day To Remember'],

    // ── The Point Stage pres. by Coors Light ────────────────────
    ['point', '13:30', '14:00', 'Doobie'],
    ['point', '14:30', '15:15', 'Pentagram'],
    ['point', '15:45', '16:30', 'Melvins'],
    ['point', '17:00', '17:50', 'Kylesa'],
    ['point', '18:20', '19:10', 'Corrosion of Conformity'],
    ['point', '19:45', '21:00', 'DOWN'],
    ['point', '21:40', '22:55', 'Black Label Society'],

    // ── Faultline Stage ─────────────────────────────────────────
    ['faultline', '11:30', '11:55', 'The Fall of Troy'],
    ['faultline', '12:20', '12:45', 'Emery'],
    ['faultline', '13:10', '13:40', 'Horse The Band'],
    ['faultline', '14:05', '14:35', 'Armor For Sleep'],
    ['faultline', '15:00', '15:40', 'Saosin'],
    ['faultline', '16:40', '17:20', 'Thursday'],
    ['faultline', '17:45', '18:30', 'La Dispute'],
    ['faultline', '19:10', '20:10', 'Circa Survive'],

    // ── Epicenter ───────────────────────────────────────────────
    ['epicenter', '12:10', '12:40', 'Gideon'],
    ['epicenter', '13:20', '13:55', 'Stick To Your Guns'],
    ['epicenter', '14:40', '15:15', 'The Acacia Strain'],
    ['epicenter', '16:00', '16:40', 'After The Burial'],
    ['epicenter', '17:30', '18:15', 'Counterparts'],
    ['epicenter', '19:15', '20:05', 'The Ghost Inside'],
  ],

  sun: [
    // ── Aftershock Stage ────────────────────────────────────────
    ['aftershock', '11:55', '12:20', 'CKY'],
    ['aftershock', '12:50', '13:20', 'Helmet'],
    ['aftershock', '14:00', '14:40', 'Buckethead'],
    ['aftershock', '15:20', '15:55', 'Zakk Sabbath'],
    ['aftershock', '16:40', '17:20', 'AFI'],
    ['aftershock', '18:15', '19:15', 'Danny Elfman'],
    ['aftershock', '20:25', '21:55', 'Tool'],

    // ── Shockwave Stage ─────────────────────────────────────────
    ['shockwave', '11:30', '11:55', 'Toadies'],
    ['shockwave', '12:20', '12:50', 'Oleander'],
    ['shockwave', '13:25', '13:55', 'Filter'],
    ['shockwave', '14:45', '15:15', 'Wolfmother'],
    ['shockwave', '16:00', '16:35', 'Highly Suspect'],
    ['shockwave', '17:25', '18:10', 'Stone Temple Pilots'],
    ['shockwave', '19:20', '20:20', 'Queens of the Stone Age'],

    // ── The Point Stage pres. by Coors Light ────────────────────
    ['point', '12:20', '12:50', 'Codefendants'],
    ['point', '13:25', '13:55', 'Cro-Mags'],
    ['point', '14:45', '15:15', 'Soulfly'],
    ['point', '15:55', '16:25', 'Municipal Waste'],
    ['point', '16:55', '17:40', 'Cavalera'],
    ['point', '18:10', '19:00', 'Suicidal Tendencies'],
    ['point', '19:35', '20:25', 'Body Count feat. Ice-T'],

    // ── Faultline Stage ─────────────────────────────────────────
    ['faultline', '11:55', '12:25', 'I Set My Friends On Fire'],
    ['faultline', '12:50', '13:20', 'Emarosa'],
    ['faultline', '13:45', '14:15', 'I See Stars'],
    ['faultline', '13:45', '14:15', 'Drop Dead, Gorgeous'],
    ['faultline', '15:40', '16:15', 'Hail The Sun'],
    ['faultline', '17:30', '18:05', 'From First To Last'],
    ['faultline', '18:55', '19:40', 'The Home Team'],
    ['faultline', '20:10', '21:10', 'Dance Gavin Dance'],

    // ── Epicenter ───────────────────────────────────────────────
    ['epicenter', '12:50', '13:20', 'Ladrones'],
    ['epicenter', '14:05', '14:40', 'The Pretty Wild'],
    ['epicenter', '15:20', '15:55', 'Holywatr'],
    ['epicenter', '16:45', '17:20', 'Jutes'],
    ['epicenter', '18:10', '18:55', 'President'],
    ['epicenter', '21:10', '21:55', 'Sleep Theory'],
  ],

};

export default {
  slug,
  name: 'Aftershock 2026',
  shortName: 'Aftershock',
  year: 2026,
  venue: 'Discovery Park, Sacramento',
  place: {
    name: 'Discovery Park',
    addressLocality: 'Sacramento',
    addressRegion: 'CA',
    addressCountry: 'US',
  },
  utcOffset: '-07:00',
  dateRange: 'October 1–4, 2026',
  officialUrl: 'https://aftershockfestival.com/schedule/',
  dataVerifiedOn: '2026-09-09',
  headliners: ['My Chemical Romance', 'Limp Bizkit', 'Pierce The Veil', 'Tool'],
  notableActs: [
    'Wu-Tang Clan',
    'Public Enemy',
    'Sublime',
    'BABYMETAL',
    'Danny Elfman',
    'AFI',
    'Dethklok',
    'Black Label Society',
    'Mayday Parade',
  ],
  stages,
  days,
  sets,
  groupNames: [
    'Aftershock Army', 'Discovery Park Pack', 'Faultline Faithful', 'Epicenter Crew',
    'Sacramento Shakers', 'Richter Scale Squad', 'Shockwave Section', 'Pit Patrol',
    'River City Riffs', 'Ground Zero Gang', 'Tremor Tribe', 'Four Day Fault',
  ],
};
