/*
 * Streaming links for the four festivals that close out the 2026 season —
 * Louder Than Life, Bourbon & Beyond, Aftershock and Sea.Hear.Now.
 *
 * Keyed by the exact artist string each festival's `sets` uses, because that
 * is what ArtistPopup looks up (`festival.artistLinks?.[name]`). One shared
 * map rather than four per-festival ones: 76 of these acts play more than
 * one of the four bills, and a single entry keeps their links from drifting
 * apart. Extra keys are harmless — a festival only ever looks up its own
 * names, the same way austin-city-limits-2026-lineup.js carries links for
 * acts not on either weekend's final schedule.
 *
 * Three of the four definitions — louder-than-life-2026.js,
 * bourbon-and-beyond-2026.js and aftershock-2026.js — are GENERATED in full by
 * scripts/gen-greencopper-festival.py, which emits no artistLinks, so links
 * written into those files would be destroyed by the next refresh. That is why
 * this map is attached in shared/festivals/index.js at registration rather
 * than imported by the festival modules themselves. sea-hear-now-2026.js is
 * hand-written and could have carried its own map, but shares this one so the
 * acts it has in common with the other three stay consistent.
 *
 * Sourced September 2026. Apple Music comes from Wikidata's Apple artist id
 * (P2850) where there is one and its id still resolves to the right name,
 * else the public iTunes Search API matched on exact artist name, with the
 * primary genre separating same-named acts. Spotify and SoundCloud come from
 * Wikidata (P1902 / P3040), falling back to MusicBrainz url-rels for acts
 * with no Wikidata item. Every Spotify and SoundCloud URL was then fetched
 * and its og:title checked against the billed name, so a stale or mis-keyed
 * id was dropped rather than shipped; the few that legitimately differ
 * (Dethklok is 'Metalocalypse: Dethklok', Jesse Welles records as 'Welles')
 * were confirmed by hand, and a few candidates that matched by name but had
 * a few hundred monthly listeners were dropped as likely impostors.
 *
 * Partial entries are normal — the popup renders whichever platforms are
 * present. Missing acts are those with no presence on any of the three
 * services, plus the Fork & Flask stage's bourbon tastings and chef demos,
 * which are billed like sets but are not musical acts. ArtistPopup omits the
 * listen row entirely for those.
 */
export default {
  '$UICIDEBOY$': { spotify: 'https://open.spotify.com/artist/1VPmR4DJC1PlOtd0IADAO0', appleMusic: 'https://music.apple.com/us/artist/%24uicideboy%24/1081606072', soundcloud: 'https://soundcloud.com/g59' },
  '156/Silence': { spotify: 'https://open.spotify.com/artist/2qXHYRTtZytxMMfO9pW1V9', appleMusic: 'https://music.apple.com/us/artist/156-silence/1071395282' },
  '200 Stab Wounds': { spotify: 'https://open.spotify.com/artist/6DH6xC3RoN7L7sGlJ60LKv', appleMusic: 'https://music.apple.com/us/artist/200-stab-wounds/1507819751', soundcloud: 'https://soundcloud.com/200stabwounds' },
  '4 Non Blondes': { spotify: 'https://open.spotify.com/artist/0Je74SitssvJg1w4Ra2EK7', appleMusic: 'https://music.apple.com/us/artist/4-non-blondes/362923' },
  '40 Below Summer': { spotify: 'https://open.spotify.com/artist/68crB0FZHHJ4skP0JgMFKF', appleMusic: 'https://music.apple.com/us/artist/40-below-summer/152916' },
  '54 Ultra': { spotify: 'https://open.spotify.com/artist/6X5L6rmyvrWWu60Gx6exiZ', appleMusic: 'https://music.apple.com/us/artist/54-ultra/1521471420' },
  'A Day To Remember': { spotify: 'https://open.spotify.com/artist/4NiJW4q9ichVqL1aUsgGAN', appleMusic: 'https://music.apple.com/us/artist/a-day-to-remember/59925710', soundcloud: 'https://soundcloud.com/adtrofficial' },
  'Adam Ant': { spotify: 'https://open.spotify.com/artist/3QP0XPDwbvGivqDAaJ5f5G', appleMusic: 'https://music.apple.com/us/artist/adam-ant/647739' },
  'Adelitas Way': { spotify: 'https://open.spotify.com/artist/1ZjAT2nTrzDIXFfsQ2hWJk', appleMusic: 'https://music.apple.com/us/artist/adelitas-way/314795012', soundcloud: 'https://soundcloud.com/adelitasway' },
  'AFI': { spotify: 'https://open.spotify.com/artist/19I4tYiChJoxEO5EuviXpz', soundcloud: 'https://soundcloud.com/afi-official' },
  'After The Burial': { spotify: 'https://open.spotify.com/artist/0uNj4RxFjG0iVPlZS753en', appleMusic: 'https://music.apple.com/us/artist/after-the-burial/210642079' },
  'Agnostic Front': { spotify: 'https://open.spotify.com/artist/3zDvanHxaETiHltPkKKYhT', appleMusic: 'https://music.apple.com/us/artist/agnostic-front/45435391' },
  'Alesana': { spotify: 'https://open.spotify.com/artist/1fnDlUNi67FQtHHqBl4Yfg', appleMusic: 'https://music.apple.com/us/artist/alesana/120993966' },
  'Alexisonfire': { spotify: 'https://open.spotify.com/artist/53RsXctnNmj9oKXvcbvzI2', appleMusic: 'https://music.apple.com/us/artist/alexisonfire/29405104' },
  'Alice Cooper': { spotify: 'https://open.spotify.com/artist/3EhbVgyfGd7HkpsagwL9GS', appleMusic: 'https://music.apple.com/us/artist/alice-cooper/393703' },
  'Alice Phoebe Lou': { spotify: 'https://open.spotify.com/artist/03uMw43UVu9MsQCcHVSGjX', appleMusic: 'https://music.apple.com/us/artist/alice-phoebe-lou/670236358', soundcloud: 'https://soundcloud.com/alicephoebelou' },
  'Alien Ant Farm': { spotify: 'https://open.spotify.com/artist/6TZdvF1kFzwnQLgHQynzsO', appleMusic: 'https://music.apple.com/us/artist/alien-ant-farm/3446405' },
  'Alkaline Trio': { spotify: 'https://open.spotify.com/artist/1aEYCT7t18aM3VvM6y8oVR', appleMusic: 'https://music.apple.com/us/artist/alkaline-trio/2901509', soundcloud: 'https://soundcloud.com/alkaline-trio-official' },
  'American Monster': { spotify: 'https://open.spotify.com/artist/4Zl6dRxUaoVz9K8egKAMFI', appleMusic: 'https://music.apple.com/us/artist/american-monster/1021709697' },
  'Amigo The Devil': { spotify: 'https://open.spotify.com/artist/0AkmSuTOzM2pNCIOSP8ziv', appleMusic: 'https://music.apple.com/us/artist/amigo-the-devil/398046580' },
  'Amos Lee': { spotify: 'https://open.spotify.com/artist/0QrowybipCKUDnq5y10PD2', appleMusic: 'https://music.apple.com/us/artist/amos-lee/45539761' },
  'Anders Osborne': { spotify: 'https://open.spotify.com/artist/3WUUtA45g7X0jbeywZz888', appleMusic: 'https://music.apple.com/us/artist/anders-osborne/761408' },
  'Angel Du$t': { spotify: 'https://open.spotify.com/artist/2ynylCO9SRPTKjgNEH0Y2a', appleMusic: 'https://music.apple.com/us/artist/angel-du%24t/657097036' },
  'Angus and Julia Stone': { spotify: 'https://open.spotify.com/artist/4tvKz56Tr39bkhcQUTO0Xr', appleMusic: 'https://music.apple.com/us/artist/angus-julia-stone/169843517' },
  'Animals As Leaders': { spotify: 'https://open.spotify.com/artist/65C6Unk7nhg2aCnVuAPMo8', appleMusic: 'https://music.apple.com/us/artist/animals-as-leaders/311508570' },
  'Anthrax': { spotify: 'https://open.spotify.com/artist/3JysSUOyfVs1UQ0UaESheP', appleMusic: 'https://music.apple.com/us/artist/anthrax/80417', soundcloud: 'https://soundcloud.com/anthrax' },
  'Apocalyptica': { spotify: 'https://open.spotify.com/artist/4Lm0pUvmisUHMdoky5ch2I', appleMusic: 'https://music.apple.com/us/artist/apocalyptica/411644', soundcloud: 'https://soundcloud.com/apocalyptica' },
  'Archers': { spotify: 'https://open.spotify.com/artist/5aJJUTEzIbxdogCW6Qpire', appleMusic: 'https://music.apple.com/us/artist/archers/961643973' },
  'Armor For Sleep': { spotify: 'https://open.spotify.com/artist/7eSbps3Uha3MMBNWhMYa2H', appleMusic: 'https://music.apple.com/us/artist/armor-for-sleep/29404808' },
  'Arrows in Action': { spotify: 'https://open.spotify.com/artist/467o5z7PYxbXFAGA0mvhAQ', appleMusic: 'https://music.apple.com/us/artist/arrows-in-action/1093697130' },
  'As You Were': { appleMusic: 'https://music.apple.com/us/artist/as-you-were/447816909' },
  'Atreyu': { spotify: 'https://open.spotify.com/artist/3LkSiHbjqOHCKCqBfEZOTv', appleMusic: 'https://music.apple.com/us/artist/atreyu/6095061', soundcloud: 'https://soundcloud.com/atreyu-official' },
  'Austin Carlile: The Original Voice of Of Mice & Men': { spotify: 'https://open.spotify.com/artist/4tususHNaR68xdgLstlGBA', appleMusic: 'https://music.apple.com/us/artist/of-mice-men/127357180' },
  'Avery Anna': { spotify: 'https://open.spotify.com/artist/5rjz63sgMaAUAyBMyCUK5D', appleMusic: 'https://music.apple.com/us/artist/avery-anna/1430307815', soundcloud: 'https://soundcloud.com/averyannamusic' },
  'Aviana': { spotify: 'https://open.spotify.com/artist/1AvLltBsz1HdAtZeucm9zy', appleMusic: 'https://music.apple.com/us/artist/aviana/270116272', soundcloud: 'https://soundcloud.com/AvianaMusic' },
  'BABYMETAL': { spotify: 'https://open.spotify.com/artist/630wzNP2OL7fl4Xl0GnMWq', appleMusic: 'https://music.apple.com/us/artist/babymetal/477101776', soundcloud: 'https://soundcloud.com/babymetalofficial' },
  'Ben Chapman': { spotify: 'https://open.spotify.com/artist/1AbQ2l8a9JEh8FrJgf1OA9', appleMusic: 'https://music.apple.com/us/artist/ben-chapman/1581192612' },
  'Ben Howard': { spotify: 'https://open.spotify.com/artist/5schNIzWdI9gJ1QRK8SBnc', appleMusic: 'https://music.apple.com/us/artist/ben-howard/432957499', soundcloud: 'https://soundcloud.com/benhowardofficial' },
  'Better Than Ezra': { spotify: 'https://open.spotify.com/artist/4UuoJfJ9UybJft7a8E6UHX', appleMusic: 'https://music.apple.com/us/artist/better-than-ezra/613039', soundcloud: 'https://soundcloud.com/betterthanezra' },
  'Between The Buried And Me': { spotify: 'https://open.spotify.com/artist/2JC4hZm1egeJDEolLsMwZ9', appleMusic: 'https://music.apple.com/us/artist/between-the-buried-and-me/107404782' },
  'Billy McNicol': { appleMusic: 'https://music.apple.com/us/artist/billy-mcnicol/602973882' },
  'Bilmuri': { spotify: 'https://open.spotify.com/artist/5Rc75vGFBWZPgL7EXb4k89', appleMusic: 'https://music.apple.com/us/artist/bilmuri/1072442999' },
  'Black Label Society': { spotify: 'https://open.spotify.com/artist/0zfT626RwO6zN3RDYeRit5', appleMusic: 'https://music.apple.com/us/artist/black-label-society/2778807', soundcloud: 'https://soundcloud.com/black-label-society' },
  'Black Veil Brides': { spotify: 'https://open.spotify.com/artist/6O7MpKrY91vlCd4Osi6XKs', appleMusic: 'https://music.apple.com/us/artist/black-veil-brides/276789923', soundcloud: 'https://soundcloud.com/black-veil-brides-official' },
  'Blessthefall': { spotify: 'https://open.spotify.com/artist/7t2C8WwLyKUKRe0LVh8zl9', appleMusic: 'https://music.apple.com/us/artist/blessthefall/202971163', soundcloud: 'https://soundcloud.com/blessthefall' },
  'Blood For Blood': { spotify: 'https://open.spotify.com/artist/1x61OF80wiXb3qawWTGUDA', appleMusic: 'https://music.apple.com/us/artist/blood-for-blood/7253942' },
  'Blue Medusa': { spotify: 'https://open.spotify.com/artist/4BMOQ1GSXhTvuv6a05wk7z', appleMusic: 'https://music.apple.com/us/artist/blue-medusa/1882057979' },
  'Body Count feat. Ice-T': { spotify: 'https://open.spotify.com/artist/5KCph1z3jaSwhtwPzoYp6i', appleMusic: 'https://music.apple.com/us/artist/body-count/645352' },
  'Bodysnatcher': { spotify: 'https://open.spotify.com/artist/2tCl0ipvwJJRJLAuIGf6tm', appleMusic: 'https://music.apple.com/us/artist/bodysnatcher/331072097', soundcloud: 'https://soundcloud.com/bodysnatcher-music' },
  'Boltcutter': { spotify: 'https://open.spotify.com/artist/79eBfUo8gsFULGBG80QRln', appleMusic: 'https://music.apple.com/us/artist/boltcutter/1696671348' },
  'Born of Osiris': { spotify: 'https://open.spotify.com/artist/4HgqjpBaWctBWVHafQIpRt', appleMusic: 'https://music.apple.com/us/artist/born-of-osiris/265002070' },
  'Boundaries': { soundcloud: 'https://soundcloud.com/boundariesdk' },
  'Bowling For Soup': { spotify: 'https://open.spotify.com/artist/5ND0mGcL9SKSjWIjPd0xIb', appleMusic: 'https://music.apple.com/us/artist/bowling-for-soup/1650849', soundcloud: 'https://soundcloud.com/bowlingforsoup' },
  'Brujeria': { spotify: 'https://open.spotify.com/artist/1VV61UepOgsPiOjljK6mBY', appleMusic: 'https://music.apple.com/us/artist/brujeria/4163922' },
  'Bryan Martin': { spotify: 'https://open.spotify.com/artist/0ChjBYedhZTQnWZWQYg15U', appleMusic: 'https://music.apple.com/us/artist/bryan-martin/1530124649' },
  'Buckethead': { spotify: 'https://open.spotify.com/artist/0fDF0jjmdouCIeWhNnblwV' },
  'Buffalo Traffic Jam': { spotify: 'https://open.spotify.com/artist/22LEPYRDhoThnbpShy6fV7', appleMusic: 'https://music.apple.com/us/artist/buffalo-traffic-jam/1744636210' },
  'Burger Battle w/ Stanley Simmons and Santos': { appleMusic: 'https://music.apple.com/us/artist/stanley-simmons/1851066844' },
  'Butcher Babies': { spotify: 'https://open.spotify.com/artist/6FcvjJzvxgybo7Ywsj0hRj', appleMusic: 'https://music.apple.com/us/artist/butcher-babies/520447521' },
  'Caitlynne Curtis': { appleMusic: 'https://music.apple.com/us/artist/caitlynne-curtis/372880763' },
  'Caleb & Reeb': { appleMusic: 'https://music.apple.com/us/artist/caleb-reeb/1874000015' },
  'Cameron Whitcomb': { spotify: 'https://open.spotify.com/artist/6dhXvR5MsnlwYguRuqoapR', appleMusic: 'https://music.apple.com/us/artist/cameron-whitcomb/1542957700', soundcloud: 'https://soundcloud.com/cameronwhitcomb' },
  'Cane Hill': { spotify: 'https://open.spotify.com/artist/0DZKzOGHDqGaf1N2pmsBRZ', appleMusic: 'https://music.apple.com/us/artist/cane-hill/925469275', soundcloud: 'https://soundcloud.com/cane-hill-official' },
  'Caskets': { spotify: 'https://open.spotify.com/artist/2XIbOWDT5vZPW7jNyzdfcK', appleMusic: 'https://music.apple.com/us/artist/caskets/1436620435' },
  'Cavalera': { appleMusic: 'https://music.apple.com/us/artist/cavalera/308589154' },
  'Chad Gray: Voice of Mudvayne & HELLYEAH': { spotify: 'https://open.spotify.com/artist/2Pfv2w8a20xzC7Dr7QXRqM', appleMusic: 'https://music.apple.com/us/artist/mudvayne/468521' },
  'Chained Saint': { spotify: 'https://open.spotify.com/artist/6JChzL9HQEspINhiTqSURd', appleMusic: 'https://music.apple.com/us/artist/chained-saint/1747613613' },
  'Chaka Khan': { spotify: 'https://open.spotify.com/artist/6mQfAAqZGBzIfrmlZCeaYT', appleMusic: 'https://music.apple.com/us/artist/chaka-khan/17402', soundcloud: 'https://soundcloud.com/chakakhan' },
  'Charley Crockett': { spotify: 'https://open.spotify.com/artist/3BJX1nYizKvWpZTY5HOAr4', appleMusic: 'https://music.apple.com/us/artist/charley-crockett/987849844', soundcloud: 'https://soundcloud.com/charleycrockett' },
  'Cheap Trick': { spotify: 'https://open.spotify.com/artist/1LB8qB5BPb3MHQrfkvifXU', appleMusic: 'https://music.apple.com/us/artist/cheap-trick/461577' },
  'Chelsea Grin': { spotify: 'https://open.spotify.com/artist/4UgQ3EFa8fEeaIEg54uV5b', appleMusic: 'https://music.apple.com/us/artist/chelsea-grin/286570387', soundcloud: 'https://soundcloud.com/chelseagrinofficial' },
  'Chiodos': { spotify: 'https://open.spotify.com/artist/4ZIBrskTJWmkJUvM7uAu1o', appleMusic: 'https://music.apple.com/us/artist/chiodos/74900736' },
  'Chris Stapleton': { spotify: 'https://open.spotify.com/artist/4YLtscXsxbVgi031ovDDdh', appleMusic: 'https://music.apple.com/us/artist/chris-stapleton/1752134', soundcloud: 'https://soundcloud.com/chris-stapleton-music' },
  'Chris Stapleton x Harlen Wheatley x Traveller Whiskey': { spotify: 'https://open.spotify.com/artist/4YLtscXsxbVgi031ovDDdh', appleMusic: 'https://music.apple.com/us/artist/chris-stapleton/1752134', soundcloud: 'https://soundcloud.com/chris-stapleton-music' },
  'Circa Survive': { spotify: 'https://open.spotify.com/artist/11FY888Qctoy6YueCpFkXT', appleMusic: 'https://music.apple.com/us/artist/circa-survive/57109037', soundcloud: 'https://soundcloud.com/circasurvive' },
  'CKY': { spotify: 'https://open.spotify.com/artist/3ZQEU2arcWXSv3oz8hwWBK', appleMusic: 'https://music.apple.com/us/artist/cky/91599', soundcloud: 'https://soundcloud.com/ckyofficial' },
  'Clover County': { spotify: 'https://open.spotify.com/artist/1vOabSI7N1elDhNGoirgU2', appleMusic: 'https://music.apple.com/us/artist/clover-county/1661364567' },
  'Coal Chamber': { spotify: 'https://open.spotify.com/artist/69k6uTSZMPLpSnhmLCiKxQ', appleMusic: 'https://music.apple.com/us/artist/coal-chamber/16638767' },
  'Codefendants': { spotify: 'https://open.spotify.com/artist/6HBfXt98QpP7QVDPLHjHTe', appleMusic: 'https://music.apple.com/us/artist/codefendants/1656143063' },
  'Coheed and Cambria': { spotify: 'https://open.spotify.com/artist/3utxjLheHaVEd9bPjQRsy8', appleMusic: 'https://music.apple.com/us/artist/coheed-and-cambria/15031628', soundcloud: 'https://soundcloud.com/coheedandcambria' },
  'Congress The Band': { appleMusic: 'https://music.apple.com/us/artist/congress-the-band/1763445097' },
  'Corpse Pile': { spotify: 'https://open.spotify.com/artist/3xUOrcghypEI9Ua6wR0tDU', appleMusic: 'https://music.apple.com/us/artist/corpse-pile/1531643362', soundcloud: 'https://soundcloud.com/corpsepile-music' },
  'Corrosion of Conformity': { spotify: 'https://open.spotify.com/artist/1BBIIH0h76KN8gYeXFcPjR', appleMusic: 'https://music.apple.com/us/artist/corrosion-of-conformity/485858', soundcloud: 'https://soundcloud.com/corrosionofconformity' },
  'Couch': { spotify: 'https://open.spotify.com/artist/3nYyLjhw4mYzYfJePsCJYJ' },
  'Counterparts': { spotify: 'https://open.spotify.com/artist/5LyRnL0rysObxDRxzSfV1z', soundcloud: 'https://soundcloud.com/counterparts-official' },
  'Counting Crows': { spotify: 'https://open.spotify.com/artist/0vEsuISMWAKNctLlUAhSZC', appleMusic: 'https://music.apple.com/us/artist/counting-crows/35719', soundcloud: 'https://soundcloud.com/countingcrows' },
  'Cracker': { spotify: 'https://open.spotify.com/artist/0ODQJS4mk7rVBJXjdqByX6', appleMusic: 'https://music.apple.com/us/artist/cracker/527625' },
  'Cradle of Filth': { spotify: 'https://open.spotify.com/artist/0NTSMFFapnyZfvmCwzcYPd', appleMusic: 'https://music.apple.com/us/artist/cradle-of-filth/3738030' },
  'Cro-Mags': { spotify: 'https://open.spotify.com/artist/5WCrzTQZ6S6EgebqI57Ilg', appleMusic: 'https://music.apple.com/us/artist/cro-mags/4110585' },
  'Currents': { spotify: 'https://open.spotify.com/artist/5pqvAI85RMxL9K0xHvSwGu' },
  'Cypress Hill': { spotify: 'https://open.spotify.com/artist/4P0dddbxPil35MNN9G2MEX', appleMusic: 'https://music.apple.com/us/artist/cypress-hill/465802', soundcloud: 'https://soundcloud.com/chxrsk' },
  'Dance Gavin Dance': { spotify: 'https://open.spotify.com/artist/6guC9FqvlVboSKTI77NG2k', appleMusic: 'https://music.apple.com/us/artist/dance-gavin-dance/204782507', soundcloud: 'https://soundcloud.com/dance-gavin-dance' },
  'Daniel Donato\'s Cosmic Country': { appleMusic: 'https://music.apple.com/us/artist/daniel-donato/353023732' },
  'Danny Elfman': { spotify: 'https://open.spotify.com/artist/5qBZETtyzfYnXOobDXbmcD', appleMusic: 'https://music.apple.com/us/artist/danny-elfman/486493', soundcloud: 'https://soundcloud.com/danny-elfman-official' },
  'Danzig': { spotify: 'https://open.spotify.com/artist/34c4iQ5tkaZKu6Sv28BTde', appleMusic: 'https://music.apple.com/us/artist/danzig/236338' },
  'Dark Divine': { spotify: 'https://open.spotify.com/artist/3CMyREgx8ZErRUydXlmCDX' },
  'Dave Matthews Band': { spotify: 'https://open.spotify.com/artist/2TI7qyDE0QfyOlnbtfDo7L', appleMusic: 'https://music.apple.com/us/artist/dave-matthews-band/60288452', soundcloud: 'https://soundcloud.com/dave-matthews-band' },
  'Dead Poet Society': { spotify: 'https://open.spotify.com/artist/31M8EXHYtEqOqVb1X7JRVe', appleMusic: 'https://music.apple.com/us/artist/dead-poet-society/583985425', soundcloud: 'https://soundcloud.com/deadpoetsociety' },
  'Death Valley Dreams': { appleMusic: 'https://music.apple.com/us/artist/death-valley-dreams/1074109141' },
  'Dethklok': { spotify: 'https://open.spotify.com/artist/7u12AuhJ5AaJIgZAZe0US8' },
  'Diamante': { spotify: 'https://open.spotify.com/artist/6jMXENspOIBHOTQNQDTxsW', appleMusic: 'https://music.apple.com/us/artist/diamante/1251231655', soundcloud: 'https://soundcloud.com/diamante-sc' },
  'Die Spitz': { spotify: 'https://open.spotify.com/artist/0zfZmpHTu0MlkkNr5KHeXE', appleMusic: 'https://music.apple.com/us/artist/die-spitz/1545875931' },
  'Doobie': { spotify: 'https://open.spotify.com/artist/1p68N0GuFAjR2IusIJWFk7', appleMusic: 'https://music.apple.com/us/artist/doobie/1783351631', soundcloud: 'https://soundcloud.com/doobie' },
  'DOWN': { spotify: 'https://open.spotify.com/artist/1m0B9ak05G0jqDY4ACLhQu', appleMusic: 'https://music.apple.com/us/artist/down/149695' },
  'Downswing': { spotify: 'https://open.spotify.com/artist/7G66JwRjTXSaNXwlnbuYZo', appleMusic: 'https://music.apple.com/us/artist/downswing/1219996618' },
  'DRAIN': { spotify: 'https://open.spotify.com/artist/7FAAkDlPg6pg0860CIDzmu' },
  'Dreamwake': { spotify: 'https://open.spotify.com/artist/7w7sMRp0FSQRRZM5SZG0Dm', appleMusic: 'https://music.apple.com/us/artist/dreamwake/1466722391' },
  'Drop Dead, Gorgeous': { spotify: 'https://open.spotify.com/artist/7ib9jRPvGJ6VPCTg35G2L9' },
  'Drowning Pool': { spotify: 'https://open.spotify.com/artist/1E4r4z7ivGUcSAnCbINJ9v', appleMusic: 'https://music.apple.com/us/artist/drowning-pool/95701594' },
  'Dry Kill Logic': { spotify: 'https://open.spotify.com/artist/01JN808vH1vhH7O7IsyRgX', appleMusic: 'https://music.apple.com/us/artist/dry-kill-logic/64811879' },
  'Durand Jones & The Indications': { spotify: 'https://open.spotify.com/artist/6TVVIyd0fsRDGg6WzHKyTP', appleMusic: 'https://music.apple.com/us/artist/durand-jones-the-indications/1054693860' },
  'Earshot': { spotify: 'https://open.spotify.com/artist/6eeYhqOX2cpsiHY6gVuvPA', appleMusic: 'https://music.apple.com/us/artist/earshot/152165', soundcloud: 'https://soundcloud.com/earshotofficial' },
  'Emarosa': { spotify: 'https://open.spotify.com/artist/68tKVjVvcqUfKFFLr2j0Ek', appleMusic: 'https://music.apple.com/us/artist/emarosa/252144676' },
  'Emery': { spotify: 'https://open.spotify.com/artist/4feAxLUxIU7G4KXhH0h2ni', appleMusic: 'https://music.apple.com/us/artist/emery/45805103' },
  'Emmure': { spotify: 'https://open.spotify.com/artist/1C62FV9Cltn9L4c9jAwCyk', appleMusic: 'https://music.apple.com/us/artist/emmure/215655584', soundcloud: 'https://soundcloud.com/emmureofficial' },
  'End It': { spotify: 'https://open.spotify.com/artist/5YlX74SFjWauq32aKLwAYn', appleMusic: 'https://music.apple.com/us/artist/end-it/1270999141' },
  'ERRA': { appleMusic: 'https://music.apple.com/us/artist/erra/408917738' },
  'Escape The Fate': { spotify: 'https://open.spotify.com/artist/5ojhEavq6altxW8fWIlLum', appleMusic: 'https://music.apple.com/us/artist/escape-the-fate/145719026', soundcloud: 'https://soundcloud.com/escape-the-fate' },
  'Eyes Set To Kill': { spotify: 'https://open.spotify.com/artist/7omnn7IRrrxdMwSwchVxNP', appleMusic: 'https://music.apple.com/us/artist/eyes-set-to-kill/271973862' },
  'Father John Misty': { spotify: 'https://open.spotify.com/artist/2kGBy2WHvF0VdZyqiVCkDT', appleMusic: 'https://music.apple.com/us/artist/father-john-misty/514361724', soundcloud: 'https://soundcloud.com/fatherjohnmisty' },
  'Fear, And Loathing in Las Vegas': { spotify: 'https://open.spotify.com/artist/5iZSZ19Lnt6iQTDITRF7Mn', appleMusic: 'https://music.apple.com/us/artist/fear-and-loathing-in-las-vegas/261086516' },
  'Filter': { spotify: 'https://open.spotify.com/artist/01WjpKiWVNurV5hjIadB8C', appleMusic: 'https://music.apple.com/us/artist/filter/125334796', soundcloud: 'https://soundcloud.com/officialfilterband' },
  'Finch': { spotify: 'https://open.spotify.com/artist/528t5c0zyuG9beehtth4Za', appleMusic: 'https://music.apple.com/us/artist/finch/1951837' },
  'Finger Eleven': { spotify: 'https://open.spotify.com/artist/0niJkG4tKkne3zwr7I8n9n', appleMusic: 'https://music.apple.com/us/artist/finger-eleven/96318432', soundcloud: 'https://soundcloud.com/fingereleven' },
  'Fireside Collective': { spotify: 'https://open.spotify.com/artist/5pTVgcphr57bYahGLO4bSC', appleMusic: 'https://music.apple.com/us/artist/fireside-collective/1241173609' },
  'Firkin Podcast with Better Than Ezra': { spotify: 'https://open.spotify.com/artist/4UuoJfJ9UybJft7a8E6UHX', appleMusic: 'https://music.apple.com/us/artist/better-than-ezra/613039', soundcloud: 'https://soundcloud.com/betterthanezra' },
  'Fit For A King': { spotify: 'https://open.spotify.com/artist/0OgdRTPItr9dw4XYp4JJUx', appleMusic: 'https://music.apple.com/us/artist/fit-for-a-king/279581764' },
  'Fitz and the Tantrums': { spotify: 'https://open.spotify.com/artist/4AcHt3JxKy59IX7JNNlZn4', appleMusic: 'https://music.apple.com/us/artist/fitz-and-the-tantrums/321144807', soundcloud: 'https://soundcloud.com/fitzandthetantrums' },
  'Flipturn': { spotify: 'https://open.spotify.com/artist/7FKTg75ADVMZgY3P9ZMRtH', appleMusic: 'https://music.apple.com/us/artist/flipturn/1152532111', soundcloud: 'https://soundcloud.com/flipturnband' },
  'Fontaines D.C.': { spotify: 'https://open.spotify.com/artist/3SXwqSqAoBz9WCI9PDQzY6', appleMusic: 'https://music.apple.com/us/artist/fontaines-d-c/1341828470', soundcloud: 'https://soundcloud.com/fontainesdublin' },
  'Foo Fighters': { spotify: 'https://open.spotify.com/artist/7jy3rLJdDQY21OgRLCZ9sD', appleMusic: 'https://music.apple.com/us/artist/foo-fighters/6906197', soundcloud: 'https://soundcloud.com/foofighters' },
  'Foster The People': { spotify: 'https://open.spotify.com/artist/7gP3bB2nilZXLfPHJhMdvc', appleMusic: 'https://music.apple.com/us/artist/foster-the-people/414023649', soundcloud: 'https://soundcloud.com/fosterthepeoplemusic' },
  'Fox Lake': { spotify: 'https://open.spotify.com/artist/7lmvHeAJ7CIhXCdLKjm7VL', soundcloud: 'https://soundcloud.com/foxlake-music' },
  'Free Throw': { spotify: 'https://open.spotify.com/artist/49b68DLRK5eCbtJf7Xx4Cc', appleMusic: 'https://music.apple.com/us/artist/free-throw/151221664', soundcloud: 'https://soundcloud.com/free-throw' },
  'Freeze The Fall': { spotify: 'https://open.spotify.com/artist/20OWAFiCJOvXwWlCBU5xHc', appleMusic: 'https://music.apple.com/us/artist/freeze-the-fall/1724866538' },
  'From Ashes To New': { spotify: 'https://open.spotify.com/artist/4HrkLxQHZ5mgCtIVpiH5QX', appleMusic: 'https://music.apple.com/us/artist/from-ashes-to-new/688645097', soundcloud: 'https://soundcloud.com/from-ashes-to-new' },
  'From First To Last': { spotify: 'https://open.spotify.com/artist/5n71fmAB8Un2IfAPn64erN', appleMusic: 'https://music.apple.com/us/artist/from-first-to-last/28673455', soundcloud: 'https://soundcloud.com/from-first-to-last' },
  'Future Palace': { spotify: 'https://open.spotify.com/artist/4QnuZOyl4C9d1keyOZXJ21', appleMusic: 'https://music.apple.com/us/artist/future-palace/1457925016', soundcloud: 'https://soundcloud.com/future_palace' },
  'Gabriella Rose': { spotify: 'https://open.spotify.com/artist/4Ff6AJhOGPhMC1wezoZNTj' },
  'Gary Clark Jr.': { spotify: 'https://open.spotify.com/artist/01aC2ikO4Xgb2LUpf9JfKp', appleMusic: 'https://music.apple.com/us/artist/gary-clark-jr/266463936', soundcloud: 'https://soundcloud.com/garyclarkjr' },
  'Gates To Hell': { spotify: 'https://open.spotify.com/artist/5LcybrMKewCzWmVWvWAauw', appleMusic: 'https://music.apple.com/us/artist/gates-to-hell/1474307662', soundcloud: 'https://soundcloud.com/gatestohell-music' },
  'Get Scared': { spotify: 'https://open.spotify.com/artist/5r9uIJCoquVtEkCkvcn8Ez', appleMusic: 'https://music.apple.com/us/artist/get-scared/322723478' },
  'Gideon': { appleMusic: 'https://music.apple.com/us/artist/gideon/186561005' },
  'Gojira': { spotify: 'https://open.spotify.com/artist/0GDGKpJFhVpcjIGF8N6Ewt', appleMusic: 'https://music.apple.com/us/artist/gojira/65158676', soundcloud: 'https://soundcloud.com/gojira1' },
  'Goo Goo Dolls': { spotify: 'https://open.spotify.com/artist/2sil8z5kiy4r76CRTXxBCA', appleMusic: 'https://music.apple.com/us/artist/the-goo-goo-dolls/147559', soundcloud: 'https://soundcloud.com/thegoogoodolls' },
  'Goose': { spotify: 'https://open.spotify.com/artist/3gAnduA93Ykv75yNrwXhz5', appleMusic: 'https://music.apple.com/us/artist/goose/152242651', soundcloud: 'https://soundcloud.com/goosemusic' },
  'Greyhaven': { spotify: 'https://open.spotify.com/artist/1zmx3NwOp6vR4qEjmhSiLL' },
  'GWAR': { spotify: 'https://open.spotify.com/artist/3dnH7fdVm2X07MK6Fkbhbt', appleMusic: 'https://music.apple.com/us/artist/gwar/28693087' },
  'H2O': { appleMusic: 'https://music.apple.com/us/artist/h2o/66698' },
  'Haarper': { spotify: 'https://open.spotify.com/artist/3v0QTRruILayLe5VsaYdvk', appleMusic: 'https://music.apple.com/us/artist/haarper/1492067829', soundcloud: 'https://soundcloud.com/haarper' },
  'Hail The Sun': { spotify: 'https://open.spotify.com/artist/0XblvrTo6mnHOxWIP1t5T6', appleMusic: 'https://music.apple.com/us/artist/hail-the-sun/382677770' },
  'Haircut 100': { spotify: 'https://open.spotify.com/artist/6imyM8T1Xbe8v2iZe41dR7', appleMusic: 'https://music.apple.com/us/artist/haircut-100/13653048' },
  'Halestorm': { spotify: 'https://open.spotify.com/artist/6om12Ev5ppgoMy3OYSoech', appleMusic: 'https://music.apple.com/us/artist/halestorm/3969358', soundcloud: 'https://soundcloud.com/halestormrocks' },
  'Haste The Day': { spotify: 'https://open.spotify.com/artist/7voCqDg5xgF1LZFrmbPS7w', appleMusic: 'https://music.apple.com/us/artist/haste-the-day/45865761' },
  'Hawthorne Heights': { spotify: 'https://open.spotify.com/artist/126FigDBtqwS2YsOYMTPQe', appleMusic: 'https://music.apple.com/us/artist/hawthorne-heights/92149634', soundcloud: 'https://soundcloud.com/hawthorneheights' },
  'HAYWIRE': { spotify: 'https://open.spotify.com/artist/5w4hQ68s8m7mLTlpnub62B', appleMusic: 'https://music.apple.com/us/artist/haywire/289322652' },
  'He Is Legend': { spotify: 'https://open.spotify.com/artist/53cAPynhUIC5WFgPPfbp2r', appleMusic: 'https://music.apple.com/us/artist/he-is-legend/7251914', soundcloud: 'https://soundcloud.com/he-is-legend-official' },
  'Heavy//Hitter': { spotify: 'https://open.spotify.com/artist/67VjKj4enx3D6auLtAZKCU', soundcloud: 'https://soundcloud.com/heavyhitterfl' },
  'Helmet': { spotify: 'https://open.spotify.com/artist/0qB0cTENhSUc0feov5qbg0', appleMusic: 'https://music.apple.com/us/artist/helmet/105500' },
  'Henrik': { appleMusic: 'https://music.apple.com/us/artist/henrik/1472563134' },
  'hey, nothing': { spotify: 'https://open.spotify.com/artist/6YWqJQS9TETSb8LgZONUzI', appleMusic: 'https://music.apple.com/us/artist/hey-nothing/1572931305', soundcloud: 'https://soundcloud.com/heynothing-music' },
  'Highly Suspect': { spotify: 'https://open.spotify.com/artist/2pqd3HsfsvcBGtHvPOg6eg', appleMusic: 'https://music.apple.com/us/artist/highly-suspect/419913603', soundcloud: 'https://soundcloud.com/highlysuspect' },
  'Holding Absence': { spotify: 'https://open.spotify.com/artist/2tl280wIokrLjabzrSKTgU', appleMusic: 'https://music.apple.com/us/artist/holding-absence/1148561527', soundcloud: 'https://soundcloud.com/holdingabsence' },
  'Holy Wars': { spotify: 'https://open.spotify.com/artist/2dTOWcCL0cYviin0Uz1lj4', appleMusic: 'https://music.apple.com/us/artist/holy-wars/987826411' },
  'Holywatr': { spotify: 'https://open.spotify.com/artist/0muUUrVzG2eMabJN2UHtZB', appleMusic: 'https://music.apple.com/us/artist/holywatr/1496026557', soundcloud: 'https://soundcloud.com/holywatr' },
  'Hootie & the Blowfish': { spotify: 'https://open.spotify.com/artist/08ct2eZF5lUPdJpHwNKWof', appleMusic: 'https://music.apple.com/us/artist/hootie-the-blowfish/204062' },
  'Hops, Hip-Hop, & Hometown Pride  w/ Nappy Roots': { spotify: 'https://open.spotify.com/artist/3tCxM1rTj2qUXsiQZxvt2I', appleMusic: 'https://music.apple.com/us/artist/nappy-roots/885525' },
  'Horse The Band': { spotify: 'https://open.spotify.com/artist/5YUQk45IjdzzQ49G1Txzkk', appleMusic: 'https://music.apple.com/us/artist/horse-the-band/80802127', soundcloud: 'https://soundcloud.com/horsetheband' },
  'Hot Mulligan': { spotify: 'https://open.spotify.com/artist/1lKZzN2d4IqiEYxyECIEHI', appleMusic: 'https://music.apple.com/us/artist/hot-mulligan/941918833' },
  'Howie Day': { spotify: 'https://open.spotify.com/artist/0ekbDNE2eOq8QiaXM34wer', appleMusic: 'https://music.apple.com/us/artist/howie-day/446234306' },
  'Hunter Hawkins': { appleMusic: 'https://music.apple.com/us/artist/hunter-hawkins/1550815972' },
  'I See Stars': { spotify: 'https://open.spotify.com/artist/3iCJOi5YKh247eutgCyLFe', appleMusic: 'https://music.apple.com/us/artist/i-see-stars/310523954' },
  'I Set My Friends On Fire': { spotify: 'https://open.spotify.com/artist/2QF7jwUc5zgjSbOTYh1xV0', appleMusic: 'https://music.apple.com/us/artist/i-set-my-friends-on-fire/266764024' },
  'Ice Nine Kills': { spotify: 'https://open.spotify.com/artist/52qKfVcIV4GS8A8Vay2xtt', appleMusic: 'https://music.apple.com/us/artist/ice-nine-kills/204318665' },
  'Icon For Hire': { spotify: 'https://open.spotify.com/artist/1Jy0lTKAQDnTklKzF0g2o7', appleMusic: 'https://music.apple.com/us/artist/icon-for-hire/443877750', soundcloud: 'https://soundcloud.com/iconforhire' },
  'Ill Niño': { spotify: 'https://open.spotify.com/artist/1xJ6l1VXgGuyZ0uhu27caF', appleMusic: 'https://music.apple.com/us/artist/ill-ni%C3%B1o/5570230' },
  'In This Moment': { spotify: 'https://open.spotify.com/artist/6tbLPxj1uQ6vsRQZI2YFCT', appleMusic: 'https://music.apple.com/us/artist/in-this-moment/204641943', soundcloud: 'https://soundcloud.com/inthismomentofficial' },
  'Insane Clown Posse': { spotify: 'https://open.spotify.com/artist/4xtWjIlVuZwTCeqVAsgEXy', appleMusic: 'https://music.apple.com/us/artist/insane-clown-posse/266434' },
  'Iron Maiden': { spotify: 'https://open.spotify.com/artist/6mdiAmATAx73kdxrNrnlao', appleMusic: 'https://music.apple.com/us/artist/iron-maiden/546381', soundcloud: 'https://soundcloud.com/ironmaidenmusic' },
  'ivri': { spotify: 'https://open.spotify.com/artist/5EjK7aUvQ9LMNqc2zXiWLS', appleMusic: 'https://music.apple.com/us/artist/ivri/1349563025', soundcloud: 'https://soundcloud.com/ivrii' },
  'Jarod Clemons': { spotify: 'https://open.spotify.com/artist/5hITuYWmhriINaWx2dsc0s', appleMusic: 'https://music.apple.com/us/artist/jarod-clemons/1553509946' },
  'Jason Isbell and the 400 Unit': { spotify: 'https://open.spotify.com/artist/3Lg3FGwBxOGuefqekQzRUf', appleMusic: 'https://music.apple.com/us/artist/jason-isbell-and-the-400-unit/301599804' },
  'Jason Scott & The High Heat': { appleMusic: 'https://music.apple.com/us/artist/jason-scott-the-high-heat/1770828691' },
  'Jesse Welles': { spotify: 'https://open.spotify.com/artist/6jobcjsqxweTygItqxfN5l', appleMusic: 'https://music.apple.com/us/artist/jesse-welles/1737507146', soundcloud: 'https://soundcloud.com/wellesmusic' },
  'Jessie Murph': { spotify: 'https://open.spotify.com/artist/2yLzlEFtIS0Q9UkyBZdQA7', appleMusic: 'https://music.apple.com/us/artist/jessie-murph/1548067332' },
  'Jet': { spotify: 'https://open.spotify.com/artist/5ypxebeHEIXjMtJb17uJlI', appleMusic: 'https://music.apple.com/us/artist/jet/2502435' },
  'Jimmy Eat World': { spotify: 'https://open.spotify.com/artist/3Ayl7mCk0nScecqOzvNp6s', appleMusic: 'https://music.apple.com/us/artist/jimmy-eat-world/3446973', soundcloud: 'https://soundcloud.com/jimmyeatworld' },
  'Joan Osborne': { spotify: 'https://open.spotify.com/artist/0djV4iaxhNfYWpH60ia85o', appleMusic: 'https://music.apple.com/us/artist/joan-osborne/107838', soundcloud: 'https://soundcloud.com/joan-osborne-official' },
  'Josey Scott: The Original Voice of SALIVA': { spotify: 'https://open.spotify.com/artist/5S6hjAxgxjsLylsTtMIimO', appleMusic: 'https://music.apple.com/us/artist/saliva/391630', soundcloud: 'https://soundcloud.com/saliva' },
  'Jutes': { spotify: 'https://open.spotify.com/artist/53fzjsJnjEKkA6TdncuIM4', appleMusic: 'https://music.apple.com/us/artist/jutes/603222293', soundcloud: 'https://soundcloud.com/jutes' },
  'Kacey Musgraves': { spotify: 'https://open.spotify.com/artist/70kkdajctXSbqSMJbQO424', appleMusic: 'https://music.apple.com/us/artist/kacey-musgraves/466044182', soundcloud: 'https://soundcloud.com/kacey-musgraves' },
  'Kaitlin Butts': { spotify: 'https://open.spotify.com/artist/6QmSTo72BYMATkQVOV1axD', appleMusic: 'https://music.apple.com/us/artist/kaitlin-butts/650660366' },
  'Kami Kehoe': { spotify: 'https://open.spotify.com/artist/2inxPY2UyH8riOrUuLklVR', appleMusic: 'https://music.apple.com/us/artist/kami-kehoe/1448056597', soundcloud: 'https://soundcloud.com/kamikehoe' },
  'Kevian Kraemer': { spotify: 'https://open.spotify.com/artist/4YuuDwJsOgciB2sYUvmo4a', appleMusic: 'https://music.apple.com/us/artist/kevian-kraemer/1594747842' },
  'Killswitch Engage': { spotify: 'https://open.spotify.com/artist/37394IP6uhnjIpsawpMu4l', appleMusic: 'https://music.apple.com/us/artist/killswitch-engage/14268438', soundcloud: 'https://soundcloud.com/killswitch-engage' },
  'Kim Gordon': { spotify: 'https://open.spotify.com/artist/3n8qeKQViV1waeCzZmS4Tx', appleMusic: 'https://music.apple.com/us/artist/kim-gordon/27266002' },
  'King 810': { spotify: 'https://open.spotify.com/artist/4LBpvfFaQzQKJU1GUVPniC', appleMusic: 'https://music.apple.com/us/artist/king-810/535492114', soundcloud: 'https://soundcloud.com/king810' },
  'King Stingray': { spotify: 'https://open.spotify.com/artist/3hA0yUEuLvjqvxtMlqznDb', appleMusic: 'https://music.apple.com/us/artist/king-stingray/1533004945', soundcloud: 'https://soundcloud.com/kingstingray' },
  'Kitchen Dwellers': { spotify: 'https://open.spotify.com/artist/5JiwO4LnQq3F6MGCRh3D31', appleMusic: 'https://music.apple.com/us/artist/kitchen-dwellers/789144425' },
  'Knocked Loose': { spotify: 'https://open.spotify.com/artist/4qrHkx5cgWIslciLXUMrYw', appleMusic: 'https://music.apple.com/us/artist/knocked-loose/862677537' },
  'KOYO': { spotify: 'https://open.spotify.com/artist/4np3dM8CSvjKhToa0Epfs9', appleMusic: 'https://music.apple.com/us/artist/koyo/1501270833' },
  'Kublai Khan TX': { spotify: 'https://open.spotify.com/artist/5BIOo2mCAokFcLHXO2Llb4', appleMusic: 'https://music.apple.com/us/artist/kublai-khan-tx/269034593' },
  'Kylesa': { spotify: 'https://open.spotify.com/artist/7mO0JGOATH8fVHvgCdZsXh', appleMusic: 'https://music.apple.com/us/artist/kylesa/26094346' },
  'L.S. Dunes': { spotify: 'https://open.spotify.com/artist/2uRjuSX3CCVJO0KBA518XG', appleMusic: 'https://music.apple.com/us/artist/l-s-dunes/1639015938' },
  'La Dispute': { spotify: 'https://open.spotify.com/artist/7lQKE6HaKQcCsgLRMhsh5W', appleMusic: 'https://music.apple.com/us/artist/la-dispute/151818067', soundcloud: 'https://soundcloud.com/la-dispute' },
  'Lacey Sturm': { spotify: 'https://open.spotify.com/artist/09LCTrVGnMsGbxexUFJoap', appleMusic: 'https://music.apple.com/us/artist/lacey-sturm/404046591' },
  'Ladrones': { spotify: 'https://open.spotify.com/artist/5KGNQQzk32VSQv9If4X7A6', appleMusic: 'https://music.apple.com/us/artist/ladrones/1617367440' },
  'Langhorne Slim': { spotify: 'https://open.spotify.com/artist/099toTcKJoywTosZr2hHjy', appleMusic: 'https://music.apple.com/us/artist/langhorne-slim/41896696' },
  'LEAP': { spotify: 'https://open.spotify.com/artist/538iX6YCTybcgzsrjDTrFi', appleMusic: 'https://music.apple.com/us/artist/leap/1510998330' },
  'Levi Turner': { spotify: 'https://open.spotify.com/artist/0QwS0oC5xcBWPmWfjGAhH6', appleMusic: 'https://music.apple.com/us/artist/levi-turner/1444711248' },
  'Like Moths To Flames': { spotify: 'https://open.spotify.com/artist/6RRpZz1uPqY9E28kmSPAhw', appleMusic: 'https://music.apple.com/us/artist/like-moths-to-flames/354095901' },
  'Limp Bizkit': { spotify: 'https://open.spotify.com/artist/165ZgPlLkK7bf5bDoFc6Sb', appleMusic: 'https://music.apple.com/us/artist/limp-bizkit/105544', soundcloud: 'https://soundcloud.com/limpbizkit' },
  'Lindsey Stirling': { spotify: 'https://open.spotify.com/artist/378dH6EszOLFShpRzAQkVM', appleMusic: 'https://music.apple.com/us/artist/lindsey-stirling/403025113', soundcloud: 'https://soundcloud.com/lindseystomp' },
  'Lisa Loeb': { spotify: 'https://open.spotify.com/artist/1TMMyiSsNzmRiZCAkVLVb2', appleMusic: 'https://music.apple.com/us/artist/lisa-loeb/115647', soundcloud: 'https://soundcloud.com/lisaloeb' },
  'Lit': { spotify: 'https://open.spotify.com/artist/5mgr0FFpvy267wKVAYg8qp', appleMusic: 'https://music.apple.com/us/artist/lit/1436407931' },
  'Live': { spotify: 'https://open.spotify.com/artist/6eoJpTIlcuxJNjV5fDzDJH', appleMusic: 'https://music.apple.com/us/artist/live/61027', soundcloud: 'https://soundcloud.com/freaks4live' },
  'Loathe': { spotify: 'https://open.spotify.com/artist/4G9wSdX0klmoHfjm9i6DLd', appleMusic: 'https://music.apple.com/us/artist/loathe/377883434' },
  'Locked Shut': { spotify: 'https://open.spotify.com/artist/5wXFJIjoTJiIcUqTrL808e', appleMusic: 'https://music.apple.com/us/artist/locked-shut/1705117156' },
  'Lou Ridley': { appleMusic: 'https://music.apple.com/us/artist/lou-ridley/1313339287' },
  'Machine Head': { spotify: 'https://open.spotify.com/artist/0lVlNsuGaOr9vMHCZIAKMt', appleMusic: 'https://music.apple.com/us/artist/machine-head/16638695', soundcloud: 'https://soundcloud.com/machinehead1' },
  'Madball': { spotify: 'https://open.spotify.com/artist/1qh6ppVtiFTKMyta0NXsjf', appleMusic: 'https://music.apple.com/us/artist/madball/7255611' },
  'Maddox Batson': { spotify: 'https://open.spotify.com/artist/6vJSPd6G272bUvUAisTCvd', appleMusic: 'https://music.apple.com/us/artist/maddox-batson/1719310687' },
  'Magoo': { spotify: 'https://open.spotify.com/artist/7pv3MRGkgkXa9Qn8sMctxT', appleMusic: 'https://music.apple.com/us/artist/magoo/59302844' },
  'Makua': { appleMusic: 'https://music.apple.com/us/artist/makua/1786549558' },
  'Many Eyes': { spotify: 'https://open.spotify.com/artist/001Hfjmktqije9a7IvGuFb', appleMusic: 'https://music.apple.com/us/artist/many-eyes/1709668562' },
  'Maoli': { appleMusic: 'https://music.apple.com/us/artist/maoli/305290663' },
  'Marcus King Band': { spotify: 'https://open.spotify.com/artist/0tgaHqkU1p7QhBUIzKXVU9', appleMusic: 'https://music.apple.com/us/artist/the-marcus-king-band/916374329' },
  'Mason Via': { appleMusic: 'https://music.apple.com/us/artist/mason-via/993918958' },
  'Mastodon': { spotify: 'https://open.spotify.com/artist/1Dvfqq39HxvCJ3GvfeIFuT', appleMusic: 'https://music.apple.com/us/artist/mastodon/65922937', soundcloud: 'https://soundcloud.com/mastodonrocks' },
  'Matt Hansen': { spotify: 'https://open.spotify.com/artist/6wlhqnATSJIc0NQ64VxOVJ', appleMusic: 'https://music.apple.com/us/artist/matt-hansen/1628580585' },
  'Max McNown': { spotify: 'https://open.spotify.com/artist/340PS4ZcZ4UCBgyrXzEjcp', appleMusic: 'https://music.apple.com/us/artist/max-mcnown/1682299543' },
  'Mayday Parade': { spotify: 'https://open.spotify.com/artist/3WfJ1OtrWI7RViX9DMyEGy', appleMusic: 'https://music.apple.com/us/artist/mayday-parade/192466619', soundcloud: 'https://soundcloud.com/maydayparade' },
  'Maylene & The Sons of Disaster': { spotify: 'https://open.spotify.com/artist/5qSQDLG1CdotFh8eWhm7yT', appleMusic: 'https://music.apple.com/us/artist/maylene-and-the-sons-of-disaster/83150484' },
  'Meels': { spotify: 'https://open.spotify.com/artist/5AH6zdOi1I9eHP2jlUHLnq', soundcloud: 'https://soundcloud.com/meelsdemos' },
  'Megadeth': { spotify: 'https://open.spotify.com/artist/1Yox196W7bzVNZI7RBaPnf', appleMusic: 'https://music.apple.com/us/artist/megadeth/488289', soundcloud: 'https://soundcloud.com/megadethofficial' },
  'Melvins': { spotify: 'https://open.spotify.com/artist/6aVjo0xHSiuW5hkasoYSR3', appleMusic: 'https://music.apple.com/us/artist/melvins/737433' },
  'Men at Work': { spotify: 'https://open.spotify.com/artist/0f3EsoviYnRKTkmayI3cux', appleMusic: 'https://music.apple.com/us/artist/men-at-work/15412031', soundcloud: 'https://soundcloud.com/men-at-work-official' },
  'Metal Church': { spotify: 'https://open.spotify.com/artist/0exvkfkATkqWOJgugTjJhP', appleMusic: 'https://music.apple.com/us/artist/metal-church/612150', soundcloud: 'https://soundcloud.com/metalchurch' },
  'Ministry': { spotify: 'https://open.spotify.com/artist/1DXylZlWbVvlckNqwvjTEt', appleMusic: 'https://music.apple.com/us/artist/ministry/609022' },
  'Missing Link': { spotify: 'https://open.spotify.com/artist/77iXzlVmGIOFyieeHf4qYZ' },
  'Moby': { spotify: 'https://open.spotify.com/artist/3OsRAKCvk37zwYcnzRf5XF', appleMusic: 'https://music.apple.com/us/artist/moby/789023', soundcloud: 'https://soundcloud.com/moby' },
  'Mumford & Sons': { spotify: 'https://open.spotify.com/artist/3gd8FJtBJtkRxdfbTu19U2', appleMusic: 'https://music.apple.com/us/artist/mumford-sons/307699986', soundcloud: 'https://soundcloud.com/mumfordandsons' },
  'Municipal Waste': { spotify: 'https://open.spotify.com/artist/2Ah9OuOj7B57gPD1cbwiaE', appleMusic: 'https://music.apple.com/us/artist/municipal-waste/81322810' },
  'Mushroomhead': { spotify: 'https://open.spotify.com/artist/18absyD7lQaXUDBXnyzU8M', appleMusic: 'https://music.apple.com/us/artist/mushroomhead/89455' },
  'My Chemical Romance': { spotify: 'https://open.spotify.com/artist/7FBcuc1gsnv6Y1nwFtNRCb', appleMusic: 'https://music.apple.com/us/artist/my-chemical-romance/14748659', soundcloud: 'https://soundcloud.com/my-chemical-romance' },
  'Nat Myers': { spotify: 'https://open.spotify.com/artist/2QMlNryks9wyxBCsBGciTS', appleMusic: 'https://music.apple.com/us/artist/nat-myers/1446778023' },
  'Nathan Bess': { spotify: 'https://open.spotify.com/artist/37Wn47Dtia6SWjmMSCNA0H', appleMusic: 'https://music.apple.com/us/artist/nathan-bess/1762308088' },
  'Nekrogoblikon': { spotify: 'https://open.spotify.com/artist/3FILKvtNoiEfCJO9qVNCNF', appleMusic: 'https://music.apple.com/us/artist/nekrogoblikon/211735139', soundcloud: 'https://soundcloud.com/nekrogoblikonofficial' },
  'Nevertel': { spotify: 'https://open.spotify.com/artist/0uTkKGuqdf7CtKlZLt9N0Y', appleMusic: 'https://music.apple.com/us/artist/nevertel/1067883496' },
  'New Found Glory': { spotify: 'https://open.spotify.com/artist/4ghjRm4M2vChDfTUycx0Ce', appleMusic: 'https://music.apple.com/us/artist/new-found-glory/65551', soundcloud: 'https://soundcloud.com/new-found-glory-official' },
  'Nine Days': { spotify: 'https://open.spotify.com/artist/306JHpIRGVaQd6OltnOzUO', appleMusic: 'https://music.apple.com/us/artist/nine-days/466452' },
  'No Resolve': { spotify: 'https://open.spotify.com/artist/7oAoGc2k7201dlU7mkhlDp', appleMusic: 'https://music.apple.com/us/artist/no-resolve/456421716', soundcloud: 'https://soundcloud.com/noresolve' },
  'Noah Cyrus': { spotify: 'https://open.spotify.com/artist/55fhWPvDiMpLnE4ZzNXZyW', appleMusic: 'https://music.apple.com/us/artist/noah-cyrus/333158887', soundcloud: 'https://soundcloud.com/noahcyrusofficial' },
  'Noah Rinker': { appleMusic: 'https://music.apple.com/us/artist/noah-rinker/1629238644' },
  'Nothing More': { spotify: 'https://open.spotify.com/artist/39VNwvlQTqE9SvgPjjnMpc', appleMusic: 'https://music.apple.com/us/artist/nothing-more/18531379', soundcloud: 'https://soundcloud.com/nothing-more' },
  'Of Monsters and Men': { spotify: 'https://open.spotify.com/artist/4dwdTW1Lfiq0cM8nBAqIIz', appleMusic: 'https://music.apple.com/us/artist/of-monsters-and-men/487906750', soundcloud: 'https://soundcloud.com/ofmonstersandmen' },
  'Oleander': { spotify: 'https://open.spotify.com/artist/7038Bglq6YmpBu6wPvQJiz', appleMusic: 'https://music.apple.com/us/artist/oleander/86406', soundcloud: 'https://soundcloud.com/oleanderband' },
  'Orianthi': { spotify: 'https://open.spotify.com/artist/0yNy8fi1yBBq526E6mx4Zs', appleMusic: 'https://music.apple.com/us/artist/orianthi/253190707' },
  'OTHERWISE': { spotify: 'https://open.spotify.com/artist/1OVyBGCKn7vObVIVPXcmLa', appleMusic: 'https://music.apple.com/us/artist/otherwise/164633854', soundcloud: 'https://soundcloud.com/otherwiserock' },
  'Our Lady Peace': { spotify: 'https://open.spotify.com/artist/1lqW59DUEKqvcHc8mVWBtH', appleMusic: 'https://music.apple.com/us/artist/our-lady-peace/475472', soundcloud: 'https://soundcloud.com/ourladypeaceofficial' },
  'P.O.D.': { spotify: 'https://open.spotify.com/artist/6KO6G41BBLTDNYOLefWTMU', appleMusic: 'https://music.apple.com/us/artist/p-o-d/626650', soundcloud: 'https://soundcloud.com/p-o-d' },
  'Paleface Swiss': { spotify: 'https://open.spotify.com/artist/467M2s2YxXdlL2ZpDUNL3A', appleMusic: 'https://music.apple.com/us/artist/paleface-swiss/1330029602', soundcloud: 'https://soundcloud.com/palefaceswiss' },
  'Palmyra': { spotify: 'https://open.spotify.com/artist/088hvWlXHIipa6ZYe0N664', appleMusic: 'https://music.apple.com/us/artist/palmyra/1561437913' },
  'Pantera': { spotify: 'https://open.spotify.com/artist/14pVkFUHDL207LzLHtSA18', appleMusic: 'https://music.apple.com/us/artist/pantera/155209', soundcloud: 'https://soundcloud.com/pantera' },
  'Papa Roach': { spotify: 'https://open.spotify.com/artist/4RddZ3iHvSpGV4dvATac9X', appleMusic: 'https://music.apple.com/us/artist/papa-roach/3445763', soundcloud: 'https://soundcloud.com/paparoach' },
  'Paula Cole': { spotify: 'https://open.spotify.com/artist/08DLZqQd6XDAVteF9nSEJ1', appleMusic: 'https://music.apple.com/us/artist/paula-cole/192621' },
  'PeelingFlesh': { spotify: 'https://open.spotify.com/artist/40DbKvYvADTiks7hZIUPHG', appleMusic: 'https://music.apple.com/us/artist/peelingflesh/1572475122', soundcloud: 'https://soundcloud.com/peelingflesh' },
  'Penelope Road': { spotify: 'https://open.spotify.com/artist/2BxNY82SWxJkGveOWm2oxH', appleMusic: 'https://music.apple.com/us/artist/penelope-road/1742324131' },
  'Pentagram': { spotify: 'https://open.spotify.com/artist/0xybuiDEYo3YuT3fLPaIyE' },
  'Pierce The Veil': { spotify: 'https://open.spotify.com/artist/4iJLPqClelZOBCBifm8Fzv', appleMusic: 'https://music.apple.com/us/artist/pierce-the-veil/258668501', soundcloud: 'https://soundcloud.com/pierce-the-veil-music' },
  'Pixies': { spotify: 'https://open.spotify.com/artist/6zvul52xwTWzilBZl6BUbT', appleMusic: 'https://music.apple.com/us/artist/pixies/2730151', soundcloud: 'https://soundcloud.com/pixiesmusic' },
  'Plain White T\'s': { spotify: 'https://open.spotify.com/artist/1g1yxsNVPhMUl9GrMjEb2o', appleMusic: 'https://music.apple.com/us/artist/plain-white-ts/16252710' },
  'Plates, Pours & Pop w/ Mei Lin, Lisa Loeb & Melissa Rift (Old Forester)': { spotify: 'https://open.spotify.com/artist/1TMMyiSsNzmRiZCAkVLVb2', appleMusic: 'https://music.apple.com/us/artist/lisa-loeb/115647', soundcloud: 'https://soundcloud.com/lisaloeb' },
  'Portugal. The Man': { spotify: 'https://open.spotify.com/artist/4kI8Ie27vjvonwaB2ePh8T', appleMusic: 'https://music.apple.com/us/artist/portugal-the-man/167649475', soundcloud: 'https://soundcloud.com/portugaltheman' },
  'Powerman 5000': { spotify: 'https://open.spotify.com/artist/5imUS9dQyCbAjUEJJ9QyWC', appleMusic: 'https://music.apple.com/us/artist/powerman-5000/1093515', soundcloud: 'https://soundcloud.com/powerman-5000' },
  'President': { spotify: 'https://open.spotify.com/artist/40nPYop0FOD9Syyu5y4dAU', appleMusic: 'https://music.apple.com/us/artist/president/1808681551' },
  'Primer 55': { spotify: 'https://open.spotify.com/artist/6jnxIScI1LhNdbLNbTDNwY', appleMusic: 'https://music.apple.com/us/artist/primer-55/414685' },
  'Psychostick': { spotify: 'https://open.spotify.com/artist/2kfVqdz3lJshqH9GUHhtMr', appleMusic: 'https://music.apple.com/us/artist/psychostick/167048229' },
  'Public Enemy': { spotify: 'https://open.spotify.com/artist/6Mo9PoU6svvhgEum7wh2Nd', appleMusic: 'https://music.apple.com/us/artist/public-enemy/36954', soundcloud: 'https://soundcloud.com/public-enemy-music' },
  'Queens of the Stone Age': { spotify: 'https://open.spotify.com/artist/4pejUc4iciQfgdX6OKulQn', appleMusic: 'https://music.apple.com/us/artist/queens-of-the-stone-age/857919', soundcloud: 'https://soundcloud.com/qotsa' },
  'Rain City Drive': { spotify: 'https://open.spotify.com/artist/4rMxZovfLSDjEL9eI2pKo7', appleMusic: 'https://music.apple.com/us/artist/rain-city-drive/882018181' },
  'Rainbow Girls': { spotify: 'https://open.spotify.com/artist/5qV8qZrppecEsKTWwCCtA7', appleMusic: 'https://music.apple.com/us/artist/the-rainbow-girls/325249511' },
  'Rattlesnake Milk': { spotify: 'https://open.spotify.com/artist/5ZTPO2c4BmAwr7Swe0qRQc', appleMusic: 'https://music.apple.com/us/artist/rattlesnake-milk/1211847805' },
  'Red': { spotify: 'https://open.spotify.com/artist/01crEa9G3pNpXZ5m7wuHOk', appleMusic: 'https://music.apple.com/us/artist/red/214135551', soundcloud: 'https://soundcloud.com/redmusiconline' },
  'Resolve': { spotify: 'https://open.spotify.com/artist/52tIYMYQgBbgOFIJHaOPxY' },
  'Rise Against': { spotify: 'https://open.spotify.com/artist/6Wr3hh341P84m3EI8qdn9O', appleMusic: 'https://music.apple.com/us/artist/rise-against/16252655', soundcloud: 'https://soundcloud.com/rise-against-official' },
  'Rivers of Nihil': { spotify: 'https://open.spotify.com/artist/3UJmyt9ApeZTmOlMvBNGLN', appleMusic: 'https://music.apple.com/us/artist/rivers-of-nihil/687192633' },
  'Ryman': { spotify: 'https://open.spotify.com/artist/1ZUNE7b5nNiN31AnJ0Smqj' },
  'S.G. Goodman': { spotify: 'https://open.spotify.com/artist/7hzn6FoCsEaUNPnPn7TJWd', appleMusic: 'https://music.apple.com/us/artist/s-g-goodman/1450439730', soundcloud: 'https://soundcloud.com/sggoodman' },
  'Sabaton': { spotify: 'https://open.spotify.com/artist/3o2dn2O0FCVsWDFSh8qxgG', appleMusic: 'https://music.apple.com/us/artist/sabaton/184065032', soundcloud: 'https://soundcloud.com/sabatonofficial' },
  'Sace6': { spotify: 'https://open.spotify.com/artist/3II4BTkM0mJbwvFxVJRdeS', appleMusic: 'https://music.apple.com/us/artist/sace6/1546898631' },
  'Saosin': { spotify: 'https://open.spotify.com/artist/1NUOfvAhA9AvsF1ISMkgHX', appleMusic: 'https://music.apple.com/us/artist/saosin/28673579' },
  'Sawyer Hill': { spotify: 'https://open.spotify.com/artist/3CwWzT9t3z7DARyhDIzwIG', appleMusic: 'https://music.apple.com/us/artist/sawyer-hill/1651349181' },
  'Scary Kids Scaring Kids': { spotify: 'https://open.spotify.com/artist/3cdos5vq3wSUR8mEvMiqq9', appleMusic: 'https://music.apple.com/us/artist/scary-kids-scaring-kids/42130562', soundcloud: 'https://soundcloud.com/scarykidsscaringkids' },
  'Scene Queen': { spotify: 'https://open.spotify.com/artist/6WandyxeDxlcOTwxtnTKP4', appleMusic: 'https://music.apple.com/us/artist/scene-queen/1563763617', soundcloud: 'https://soundcloud.com/scenequeen-music' },
  'Senses Fail': { spotify: 'https://open.spotify.com/artist/591yCCsZCLXvaJ0Rg38vLZ', appleMusic: 'https://music.apple.com/us/artist/senses-fail/15138873' },
  'Sent By Ravens': { appleMusic: 'https://music.apple.com/us/artist/sent-by-ravens/219804091' },
  'Set For Tomorrow': { spotify: 'https://open.spotify.com/artist/38G81lySCkQhDVRchYGZzK', appleMusic: 'https://music.apple.com/us/artist/set-for-tomorrow/574637682' },
  'Set It Off': { spotify: 'https://open.spotify.com/artist/06bDwgCHeMAwhgI8il4Y5k', appleMusic: 'https://music.apple.com/us/artist/set-it-off/124991353', soundcloud: 'https://soundcloud.com/setitoff' },
  'Sevendust': { spotify: 'https://open.spotify.com/artist/35Uu85Pq33mK8x1jYqsHY2', appleMusic: 'https://music.apple.com/us/artist/sevendust/13125174', soundcloud: 'https://soundcloud.com/sevendust' },
  'Shaggy': { spotify: 'https://open.spotify.com/artist/5EvFsr3kj42KNv97ZEnqij', appleMusic: 'https://music.apple.com/us/artist/shaggy/68616', soundcloud: 'https://soundcloud.com/direalshaggy' },
  'Shelby Means': { appleMusic: 'https://music.apple.com/us/artist/shelby-means/1451726880' },
  'Showing Teeth': { spotify: 'https://open.spotify.com/artist/6NmmsGOQdDqyXlNVA6uGWv', appleMusic: 'https://music.apple.com/us/artist/showing-teeth/1846962760' },
  'Sierra Hull': { spotify: 'https://open.spotify.com/artist/0JGGxsAD1Eg4X9AcKNcxEB', appleMusic: 'https://music.apple.com/us/artist/sierra-hull/278182972' },
  'Signs of the Swarm': { spotify: 'https://open.spotify.com/artist/0yxJx8OEyDfd7dzLsFuNrS', appleMusic: 'https://music.apple.com/us/artist/signs-of-the-swarm/1109559990', soundcloud: 'https://soundcloud.com/signsoftheswarm' },
  'Silly Goose': { spotify: 'https://open.spotify.com/artist/0GicbfMtwhn3Ch0PdwkADQ', appleMusic: 'https://music.apple.com/us/artist/silly-goose/1584399710' },
  'Skillet': { spotify: 'https://open.spotify.com/artist/49bzE5vRBRIota4qeHtQM8', appleMusic: 'https://music.apple.com/us/artist/skillet/1750802', soundcloud: 'https://soundcloud.com/skilletofficial' },
  'Slaughter to Prevail': { spotify: 'https://open.spotify.com/artist/24Oiw7BlvO1BETecDLJt6m', appleMusic: 'https://music.apple.com/us/artist/slaughter-to-prevail/1000804900' },
  'Sleep Theory': { spotify: 'https://open.spotify.com/artist/26eBHxdouBH2KB7P6Oi9HN', appleMusic: 'https://music.apple.com/us/artist/sleep-theory/1624884753' },
  'Sleeping with Sirens': { spotify: 'https://open.spotify.com/artist/3N8Hy6xQnQv1F1XCiyGQqA', appleMusic: 'https://music.apple.com/us/artist/sleeping-with-sirens/360773035', soundcloud: 'https://soundcloud.com/sleeping-with-sirens-official' },
  'Soil': { spotify: 'https://open.spotify.com/artist/4PoYwGOztIrPpBfRIlMSxP', appleMusic: 'https://music.apple.com/us/artist/soil/1116779' },
  'Sons of Legion': { spotify: 'https://open.spotify.com/artist/4WBCjNjq0MGPsvcXyOPWKW', appleMusic: 'https://music.apple.com/us/artist/sons-of-legion/1532761840' },
  'Soulfly': { spotify: 'https://open.spotify.com/artist/6159IBm5gLPwG4BcJXseXc', appleMusic: 'https://music.apple.com/us/artist/soulfly/15772893', soundcloud: 'https://soundcloud.com/soulfly-15' },
  'Spaghetti Tattoo: A Fork & Flask Welcome  w/ Plain White T\'s': { spotify: 'https://open.spotify.com/artist/1g1yxsNVPhMUl9GrMjEb2o', appleMusic: 'https://music.apple.com/us/artist/plain-white-ts/16252710' },
  'Spite': { soundcloud: 'https://soundcloud.com/spite21351' },
  'Spoken': { spotify: 'https://open.spotify.com/artist/0Jn8rIJ5ebXnyZh9s5bI4l', appleMusic: 'https://music.apple.com/us/artist/spoken/877877', soundcloud: 'https://soundcloud.com/spoken_music' },
  'Squeeze': { spotify: 'https://open.spotify.com/artist/6Jrj26oAY96EEC2lqC6fua', appleMusic: 'https://music.apple.com/us/artist/squeeze/93650' },
  'St. Paul & The Broken Bones': { spotify: 'https://open.spotify.com/artist/4fXkvh05wFhuH77MfD4m9o', appleMusic: 'https://music.apple.com/us/artist/st-paul-the-broken-bones/795004362' },
  'Stanley Simmons': { spotify: 'https://open.spotify.com/artist/2YvuPht4GYx8OU31twTCsR', appleMusic: 'https://music.apple.com/us/artist/stanley-simmons/1851066844', soundcloud: 'https://soundcloud.com/stanleysimmons' },
  'Starset': { spotify: 'https://open.spotify.com/artist/0kD8IT1CzF7js2XKM9lLLa', appleMusic: 'https://music.apple.com/us/artist/starset/669248603', soundcloud: 'https://soundcloud.com/starset-official' },
  'Status Green': { appleMusic: 'https://music.apple.com/us/artist/status-green/210186049' },
  'Stella Lefty': { spotify: 'https://open.spotify.com/artist/6hp2uD84OrQ3u3ukmTjLz2', appleMusic: 'https://music.apple.com/us/artist/stella-lefty/1641742186' },
  'Steph Strings': { appleMusic: 'https://music.apple.com/us/artist/steph-strings/1599174072' },
  'Stick To Your Guns': { spotify: 'https://open.spotify.com/artist/2sqrupqcoipb7UzVKApEnJ', appleMusic: 'https://music.apple.com/us/artist/stick-to-your-guns/218293843', soundcloud: 'https://soundcloud.com/stick-to-your-guns' },
  'Still Unknown': { appleMusic: 'https://music.apple.com/us/artist/still-unknown/1231801217' },
  'Stone Temple Pilots': { spotify: 'https://open.spotify.com/artist/2UazAtjfzqBF0Nho2awK4z', appleMusic: 'https://music.apple.com/us/artist/stone-temple-pilots/889772', soundcloud: 'https://soundcloud.com/stpsoundcloud' },
  'Sublime': { spotify: 'https://open.spotify.com/artist/0EdvGhlC1FkGItLOWQzG4J', appleMusic: 'https://music.apple.com/us/artist/sublime/63480' },
  'Suicidal Tendencies': { spotify: 'https://open.spotify.com/artist/3WPKDlucMsXH6FC1XaclZC', appleMusic: 'https://music.apple.com/us/artist/suicidal-tendencies/484609', soundcloud: 'https://soundcloud.com/suicidal-tendencies-official' },
  'Sunami': { appleMusic: 'https://music.apple.com/us/artist/sunami/1556091242', soundcloud: 'https://soundcloud.com/callmesunami' },
  'Surfaced': { spotify: 'https://open.spotify.com/artist/1gg2q0OU3yyCcHkszJxcGe', appleMusic: 'https://music.apple.com/us/artist/surfaced/1673853896' },
  'Susanna Hoffs': { spotify: 'https://open.spotify.com/artist/2Sc4ukCRllIu02LZfHF0RL', appleMusic: 'https://music.apple.com/us/artist/susanna-hoffs/827022' },
  'Taking Back Sunday': { spotify: 'https://open.spotify.com/artist/24XtlMhEMNdi822vi0MhY1', appleMusic: 'https://music.apple.com/us/artist/taking-back-sunday/16053322', soundcloud: 'https://soundcloud.com/takingbacksunday' },
  'Tantric': { spotify: 'https://open.spotify.com/artist/4tMZahYVKJdjbC1GHVtNnV', appleMusic: 'https://music.apple.com/us/artist/tantric/1248961', soundcloud: 'https://soundcloud.com/tantric-official' },
  'Texas Hippie Coalition': { spotify: 'https://open.spotify.com/artist/6LG6fIvh2XpjqHUuR7NRtt', appleMusic: 'https://music.apple.com/us/artist/texas-hippie-coalition/275099992', soundcloud: 'https://soundcloud.com/texas-hippie-coalition' },
  'The Acacia Strain': { spotify: 'https://open.spotify.com/artist/4tDkeVxH0CSkNiLVrsYmQs', appleMusic: 'https://music.apple.com/us/artist/the-acacia-strain/253042890' },
  'The All-American Rejects': { spotify: 'https://open.spotify.com/artist/3vAaWhdBR38Q02ohXqaNHT', appleMusic: 'https://music.apple.com/us/artist/the-all-american-rejects/3447642', soundcloud: 'https://soundcloud.com/the-all-american-rejects' },
  'The Ataris': { spotify: 'https://open.spotify.com/artist/3LC8PXXgk7YtAIobtjSdNi', appleMusic: 'https://music.apple.com/us/artist/the-ataris/1046357', soundcloud: 'https://soundcloud.com/the-ataris' },
  'The Barbarians of California': { spotify: 'https://open.spotify.com/artist/4ssLjypWLLQ2kP9aHRMraO', appleMusic: 'https://music.apple.com/us/artist/the-barbarians-of-california/1724096474' },
  'The Black Dahlia Murder': { spotify: 'https://open.spotify.com/artist/4xTDPgk4jHCF0qui3dH6BS', appleMusic: 'https://music.apple.com/us/artist/the-black-dahlia-murder/53265055', soundcloud: 'https://soundcloud.com/the-black-dahlia-murder' },
  'The Creekers': { spotify: 'https://open.spotify.com/artist/2Ee2dvrxHJvnpWgaqC5T0i', appleMusic: 'https://music.apple.com/us/artist/the-creekers/1653450262' },
  'The Devil Makes Three': { spotify: 'https://open.spotify.com/artist/63knPlGzLHTNDf1J78Fvte', appleMusic: 'https://music.apple.com/us/artist/the-devil-makes-three/31268207' },
  'The Devil Wears Prada': { spotify: 'https://open.spotify.com/artist/0NbQe5CNgh4YApOCDuHSjb', appleMusic: 'https://music.apple.com/us/artist/the-devil-wears-prada/189224243', soundcloud: 'https://soundcloud.com/tdwp' },
  'The Fall of Troy': { spotify: 'https://open.spotify.com/artist/5fuQrhMRYMtoO9uOlFad4P', appleMusic: 'https://music.apple.com/us/artist/the-fall-of-troy/21865177' },
  'The Flaming Lips': { spotify: 'https://open.spotify.com/artist/16eRpMNXSQ15wuJoeqguaB', appleMusic: 'https://music.apple.com/us/artist/the-flaming-lips/156604', soundcloud: 'https://soundcloud.com/theflaminglipsofficial' },
  'The Fork & Flask Yacht Club -  One Last Pour with Yachtley Crew': { spotify: 'https://open.spotify.com/artist/1MKnjx7jf1vRZEUz6gfQv5', appleMusic: 'https://music.apple.com/us/artist/y%C3%A4chtley-cr%C3%ABw/1620098668' },
  'The Fray': { spotify: 'https://open.spotify.com/artist/0zOcE3mg9nS6l3yxt1Y0bK', appleMusic: 'https://music.apple.com/us/artist/the-fray/31239777', soundcloud: 'https://soundcloud.com/the_fray' },
  'The Fretliners': { spotify: 'https://open.spotify.com/artist/4iMEdosOM4PPgZrreSoWJn', appleMusic: 'https://music.apple.com/us/artist/the-fretliners/1706384107' },
  'The Funeral Portrait': { spotify: 'https://open.spotify.com/artist/4iGsihTcyZ80RQFZhC8bf8', appleMusic: 'https://music.apple.com/us/artist/the-funeral-portrait/917467004' },
  'The Ghost Inside': { spotify: 'https://open.spotify.com/artist/6kQB2RN7WwryMdJ1MoQh1E', appleMusic: 'https://music.apple.com/us/artist/the-ghost-inside/276963639' },
  'The Home Team': { appleMusic: 'https://music.apple.com/us/artist/the-home-team/1351116388', soundcloud: 'https://soundcloud.com/thehometeamnw' },
  'The Infamous Stringdusters': { spotify: 'https://open.spotify.com/artist/7yTltkMBvChBkA86Tz8WfW', appleMusic: 'https://music.apple.com/us/artist/the-infamous-stringdusters/209591048' },
  'The Mars Volta': { spotify: 'https://open.spotify.com/artist/75U40yZLLPglFgXbDVnmVs', appleMusic: 'https://music.apple.com/us/artist/the-mars-volta/1645800' },
  'The Offspring': { spotify: 'https://open.spotify.com/artist/5LfGQac0EIXyAN8aUwmNAQ', appleMusic: 'https://music.apple.com/us/artist/the-offspring/2820865', soundcloud: 'https://soundcloud.com/offspring' },
  'The Pretty Reckless': { spotify: 'https://open.spotify.com/artist/2R57sY41L9XvGPiIgHOaYq', appleMusic: 'https://music.apple.com/us/artist/the-pretty-reckless/363203347' },
  'The Pretty Wild': { spotify: 'https://open.spotify.com/artist/4DJ2QHcDJiDC0Kx1xZ9oNm' },
  'The Prodigy': { spotify: 'https://open.spotify.com/artist/4k1ELeJKT1ISyDv8JivPpB', appleMusic: 'https://music.apple.com/us/artist/the-prodigy/1093102', soundcloud: 'https://soundcloud.com/theprodigy' },
  'The Rasmus': { spotify: 'https://open.spotify.com/artist/76ptJV8617638xrpeoUtzl', appleMusic: 'https://music.apple.com/us/artist/the-rasmus/6929309', soundcloud: 'https://soundcloud.com/the-rasmus-official' },
  'The Red Clay Strays': { spotify: 'https://open.spotify.com/artist/6IKlXZEFOvk9itrP1s0knJ', appleMusic: 'https://music.apple.com/us/artist/the-red-clay-strays/1483812664' },
  'The Red Jumpsuit Apparatus': { spotify: 'https://open.spotify.com/artist/1SImpQO0GbjRgvlwCcCtFo', appleMusic: 'https://music.apple.com/us/artist/the-red-jumpsuit-apparatus/130037074' },
  'The Search with Derek Trucks': { spotify: 'https://open.spotify.com/artist/1xJPYI7GXasA3ariMSftPq', appleMusic: 'https://music.apple.com/us/artist/derek-trucks/158040680' },
  'The Starting Line': { spotify: 'https://open.spotify.com/artist/3E3xrZtBU5ORqcmX78v5YZ' },
  'The Steel Wheels': { appleMusic: 'https://music.apple.com/us/artist/the-steel-wheels/350042758' },
  'The Stews': { spotify: 'https://open.spotify.com/artist/4yUYrN1PFyzwUDSzEpYYEi' },
  'The Story So Far': { spotify: 'https://open.spotify.com/artist/6meTcQ79DrfkIuSLPZkpBg', appleMusic: 'https://music.apple.com/us/artist/the-story-so-far/280522018', soundcloud: 'https://soundcloud.com/thestorysofarofficial' },
  'The Strokes': { spotify: 'https://open.spotify.com/artist/0epOFNiUfyON9EYx7Tpr6V', appleMusic: 'https://music.apple.com/us/artist/the-strokes/560289', soundcloud: 'https://soundcloud.com/thestrokes' },
  'The Union Underground': { spotify: 'https://open.spotify.com/artist/54akiBa0DkNM3qkhnGRflb', appleMusic: 'https://music.apple.com/us/artist/the-union-underground/467007' },
  'The Used': { spotify: 'https://open.spotify.com/artist/55VydwMyCuGcavwPuhutPL', appleMusic: 'https://music.apple.com/us/artist/the-used/799141', soundcloud: 'https://soundcloud.com/theusedband' },
  'The Verve Pipe': { spotify: 'https://open.spotify.com/artist/242iqFnwNhlidVBMI9GYKp', appleMusic: 'https://music.apple.com/us/artist/the-verve-pipe/174388' },
  'The Violent Hour': { spotify: 'https://open.spotify.com/artist/6AYAVPQMmNmjLz30CpTc9L', appleMusic: 'https://music.apple.com/us/artist/the-violent-hour/1802068825' },
  'The War on Drugs': { spotify: 'https://open.spotify.com/artist/6g0mn3tzAds6aVeUYRsryU', appleMusic: 'https://music.apple.com/us/artist/the-war-on-drugs/282078681', soundcloud: 'https://soundcloud.com/thewarondrugs' },
  'The Warning': { spotify: 'https://open.spotify.com/artist/2SmW1lFlBJn4IfBzBZDlSh', appleMusic: 'https://music.apple.com/us/artist/the-warning/260719953' },
  'The Wonder Years': { spotify: 'https://open.spotify.com/artist/0nq64XZMWV1s7XHXIkdH7K', soundcloud: 'https://soundcloud.com/the-wonder-years-official' },
  'The Word Alive': { spotify: 'https://open.spotify.com/artist/1CF8aEN939swnuIZGFI7Hk', appleMusic: 'https://music.apple.com/us/artist/the-word-alive/320531813', soundcloud: 'https://soundcloud.com/thewordalive' },
  'Theory of a Deadman': { spotify: 'https://open.spotify.com/artist/74eX4C98E4FCrAMl39qRsJ', appleMusic: 'https://music.apple.com/us/artist/theory-of-a-deadman/16169450', soundcloud: 'https://soundcloud.com/theoryofadeadman' },
  'Thousand Below': { spotify: 'https://open.spotify.com/artist/0iU3WDujScAofxcK2EMypN', appleMusic: 'https://music.apple.com/us/artist/thousand-below/1199243583' },
  'Three 6 Mafia': { spotify: 'https://open.spotify.com/artist/26s8LSolLfCIY88ysQbIuT', appleMusic: 'https://music.apple.com/us/artist/three-6-mafia/1889116', soundcloud: 'https://soundcloud.com/three-6-mafia' },
  'Thrice': { spotify: 'https://open.spotify.com/artist/3NChzMpu9exTlNPiqUQ2DE', appleMusic: 'https://music.apple.com/us/artist/thrice/1663706', soundcloud: 'https://soundcloud.com/thriceofficial' },
  'Thursday': { spotify: 'https://open.spotify.com/artist/61awhbNK16ku1uQyXRsQj5', soundcloud: 'https://soundcloud.com/thursday-official' },
  'Toadies': { spotify: 'https://open.spotify.com/artist/2QMMktUMtwMSwUZATX1cRO', appleMusic: 'https://music.apple.com/us/artist/toadies/105638', soundcloud: 'https://soundcloud.com/the-toadies' },
  'Tom Morello': { spotify: 'https://open.spotify.com/artist/74NBPbyyftqJ4SpDZ4c1Ed', appleMusic: 'https://music.apple.com/us/artist/tom-morello/466357', soundcloud: 'https://soundcloud.com/tom-morello' },
  'Tom Odell': { spotify: 'https://open.spotify.com/artist/2txHhyCwHjUEpJjWrEyqyX', appleMusic: 'https://music.apple.com/us/artist/tom-odell/524929515', soundcloud: 'https://soundcloud.com/tomodell' },
  'Tonic': { spotify: 'https://open.spotify.com/artist/6qXwLwTLdA44HYsA26vaNU' },
  'Tool': { spotify: 'https://open.spotify.com/artist/2yEwvVSSSUkcLeSTNyHKh8', appleMusic: 'https://music.apple.com/us/artist/tool/140870416', soundcloud: 'https://soundcloud.com/officialtool' },
  'Traverse The Abyss': { spotify: 'https://open.spotify.com/artist/5TSjEQ9V2ptSrrcOXRVH3H', appleMusic: 'https://music.apple.com/us/artist/traverse-the-abyss/1175403013' },
  'Twitching Tongues': { spotify: 'https://open.spotify.com/artist/3k1tPUpSlWppOSbIV1ivQy', appleMusic: 'https://music.apple.com/us/artist/twitching-tongues/428128911' },
  'TX2': { spotify: 'https://open.spotify.com/artist/1QQ0zBYrjIUnXvHf5iiV5H', appleMusic: 'https://music.apple.com/us/artist/tx2/1136613368' },
  'Uncle Lucius': { spotify: 'https://open.spotify.com/artist/49zZ2lRNpfwWfUnASUxCYW', appleMusic: 'https://music.apple.com/us/artist/uncle-lucius/199972677' },
  'Underoath': { spotify: 'https://open.spotify.com/artist/3GzWhE2xadJiW8MqRKIVSK', appleMusic: 'https://music.apple.com/us/artist/underoath/1750355', soundcloud: 'https://soundcloud.com/underoath' },
  'Vana': { spotify: 'https://open.spotify.com/artist/6o2D1YBpFJDDaMwZYGyW3T', appleMusic: 'https://music.apple.com/us/artist/vana/1571331866' },
  'Vertical Horizon': { spotify: 'https://open.spotify.com/artist/6Hizgjo92FnMp8wGaRUNTn', appleMusic: 'https://music.apple.com/us/artist/vertical-horizon/214998' },
  'vianova': { spotify: 'https://open.spotify.com/artist/01DWiz55UPC4lQOGIo4z5n' },
  'Vickie Vaughn Band': { appleMusic: 'https://music.apple.com/us/artist/vickie-vaughn-band/1037546841' },
  'Violent Femmes': { spotify: 'https://open.spotify.com/artist/0rpMdBzQXf7aYRnu5fDBJy', appleMusic: 'https://music.apple.com/us/artist/violent-femmes/168655' },
  'Volumes': { spotify: 'https://open.spotify.com/artist/1DgmdsnwOexqTH8ohPCFAU', appleMusic: 'https://music.apple.com/us/artist/volumes/207478844' },
  'Wage War': { spotify: 'https://open.spotify.com/artist/6bu7CtcOMWcS0BMq7snHW6', appleMusic: 'https://music.apple.com/us/artist/wage-war/1000847729' },
  'We The Kings': { spotify: 'https://open.spotify.com/artist/3ao3jf5d70Tf4fPh2bnXVl', appleMusic: 'https://music.apple.com/us/artist/we-the-kings/264468838', soundcloud: 'https://soundcloud.com/we-the-kings-official' },
  'Wind Walkers': { spotify: 'https://open.spotify.com/artist/2K2bsaNeuQAFkuVwrrlJe0', appleMusic: 'https://music.apple.com/us/artist/wind-walkers/1073744484' },
  'Wolfmother': { spotify: 'https://open.spotify.com/artist/3yEnArbNHyTCwMRvD9SBy4', appleMusic: 'https://music.apple.com/us/artist/wolfmother/27076064', soundcloud: 'https://soundcloud.com/official-wolfmother' },
  'Wood Box Heroes': { spotify: 'https://open.spotify.com/artist/2ywJwGJPEbhirJb831dHtH', appleMusic: 'https://music.apple.com/us/artist/wood-box-heroes/1666425983' },
  'World Famous Pets': { appleMusic: 'https://music.apple.com/us/artist/world-famous-pets/1896255592' },
  'Wu-Tang Clan': { spotify: 'https://open.spotify.com/artist/34EP7KEpOjXcM2TCat1ISk', appleMusic: 'https://music.apple.com/us/artist/wu-tang-clan/200986' },
  'Yachtley Crew': { spotify: 'https://open.spotify.com/artist/1MKnjx7jf1vRZEUz6gfQv5', appleMusic: 'https://music.apple.com/us/artist/y%C3%A4chtley-cr%C3%ABw/1620098668' },
  'Zakk Sabbath': { spotify: 'https://open.spotify.com/artist/5NeP9ggeDD2k0dy7ivp0bN', appleMusic: 'https://music.apple.com/us/artist/zakk-sabbath/1534153761' },
  'Zero 9:36': { spotify: 'https://open.spotify.com/artist/1V599H9vfq6hWe2hGzyzI0', appleMusic: 'https://music.apple.com/us/artist/zero-9-36/1479131967' },
  'Ziggy Marley': { spotify: 'https://open.spotify.com/artist/0o0rlxlC3ApLWsxFkUjMXc', appleMusic: 'https://music.apple.com/us/artist/ziggy-marley/74195147' },
  'Ünloco': { spotify: 'https://open.spotify.com/artist/1XFVzEMC5dyIus9DaPpAdK', appleMusic: 'https://music.apple.com/us/artist/unloco/1054086' },
};
