/*
 * Post-build: generate the app-shell Service Worker.
 *
 * Vite emits content-hashed filenames (dist/assets/index-XXXX.js), a fresh
 * set every build, so the precache list and a cache-busting version can only
 * be computed after `vite build` has run — this mirrors build-pages.js,
 * which does the same thing for per-festival HTML.
 *
 * The generated dist/sw.js only ever precaches the app shell (the JS/CSS
 * bundle plus the `/` document, which is enough for the SPA to boot offline
 * off any URL — see the client-side routing in App.jsx). It deliberately
 * ignores everything under /api/: that traffic is cached and invalidated by
 * client/src/api.js instead, so there is exactly one place that knows how to
 * evict stale group/vote data rather than two.
 */
import { readdirSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DIST = path.join(ROOT, 'dist');

export function buildSw({ dist = DIST, log = console.log } = {}) {
  const assetFiles = readdirSync(path.join(dist, 'assets')).sort();
  const precacheUrls = ['/', ...assetFiles.map((f) => `/assets/${f}`)];
  // Changes exactly when a deploy changes the asset list — stable across
  // rebuilds that produce identical output.
  const version = createHash('sha256').update(assetFiles.join(',')).digest('hex').slice(0, 12);

  writeFileSync(path.join(dist, 'sw.js'), swSource(version, precacheUrls));
  log(`[build-sw] app-shell-${version}, ${precacheUrls.length} urls precached`);
  return { version, precacheUrls };
}

function swSource(version, precacheUrls) {
  return `// Generated by scripts/build-sw.js — do not edit by hand.
const CACHE_NAME = 'app-shell-${version}';
const PRECACHE_URLS = ${JSON.stringify(precacheUrls)};

self.addEventListener('install', (event) => {
  self.skipWaiting();
  event.waitUntil(caches.open(CACHE_NAME).then((c) => c.addAll(PRECACHE_URLS)));
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    // Only ever sweep our own app-shell caches — client/src/offline-cache.js
    // owns a separate cache ('brsp-offline-v1') in this same Cache Storage
    // bucket for group/vote data, and it must survive every SW deploy.
    const keys = await caches.keys();
    await Promise.all(
      keys
        .filter((k) => k.startsWith('app-shell-') && k !== CACHE_NAME)
        .map((k) => caches.delete(k)),
    );
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  if (url.pathname.startsWith('/api/')) return;

  if (request.mode === 'navigate') {
    // Network-first: a live server always wins. Offline falls back to the
    // precached shell — the SPA renders the right screen off any URL once
    // React mounts, since routing happens entirely client-side.
    event.respondWith(
      fetch(request).catch(() => caches.match('/', { cacheName: CACHE_NAME })),
    );
    return;
  }

  if (url.pathname.startsWith('/assets/')) {
    // Cache-first: filenames are content-hashed, so a cache hit is always
    // byte-identical to what a network fetch would return.
    event.respondWith(
      caches.match(request, { cacheName: CACHE_NAME }).then((cached) => cached
        || fetch(request).then((res) => {
          caches.open(CACHE_NAME).then((c) => c.put(request, res.clone()));
          return res;
        })),
    );
  }
});
`;
}

// Only run when invoked directly, so tests can import buildSw().
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  buildSw();
}
